/*
 * The interface in German.
 *
 * Entries by ID from ui_text.def; one missing shows the English.  The
 * register is an instrument's: short, a noun where a label will do, the
 * imperative where an instruction is needed, no "Sie".  The terms the field
 * uses in English stay English and are not in this table: ARM, DISARM,
 * STOP, the screen titles, protocol and mode names, units, Sweep, Hold,
 * Frame Rate, Throttle, Endpoint, CSV.  One German word per concept across
 * every screen: docs/Language.md holds the glossary.
 *
 * An uppercase label writes the sharp s as SS (SCHLIESSEN for schließen);
 * mixed-case text writes ß.  UTF-8 throughout.
 *
 * SPDX-License-Identifier: MIT
 */

#include "ui_text.h"

static const char *const k_text[TX_COUNT] = {
    /* -------------------------------------------------------- shared words */
    [TX_ON]                     = "EIN",
    [TX_OFF]                    = "AUS",
    [TX_CANCEL]                 = "ABBRECHEN",
    [TX_SPACE]                  = "LEERZEICHEN",

    /* ---------------------------------------------------------- the band */
    [TX_BAND_SAFE]              = "SAFE",
    [TX_BAND_FAULT]             = "FEHLER %02X",
    [TX_BAND_NO_LINK]           = "KEIN LINK",

    /* ----------------------------------------------------------- keypads */
    [TX_KEYPAD_RANGE]           = "%.*f bis %.*f %s",
    [TX_TEXTKEY_COUNT]          = "%d von %d",
    [TX_TEXTKEY_NEEDED]         = "Name erforderlich",

    /* ---------------------------------------------------------- overview */
    [TX_OV_MOTOR]               = "Antrieb V/A rpm",
    [TX_OV_SERVO]               = "Weg, Strom",
    [TX_OV_SUPPLY]              = "Setzen, Log V/A",
    [TX_OV_ANALYSER]            = "Busse, Frames",
    [TX_OV_LOGS]                = "Schreiben, Lesen",
    [TX_OV_SETUP]               = "Akku und Ausgang",
    [TX_OV_BATTERY]             = "Zellen, iR, mAh",
    [TX_OV_BALANCE]             = "Vibration, Phase",
    [TX_OV_PROGRAMMER]          = "ESC und Servo",
    [TX_OV_MODELLED]            = "SIMULIERT",
    [TX_OV_SOON]                = "BALD",

    /* ---------------------------------------------------------- splash */
    [TX_SPLASH_BOARD]           = "PLATINE",
    [TX_SPLASH_DISPLAY]         = "DISPLAY",
    [TX_SPLASH_TOUCH]           = "TOUCH",
    [TX_SPLASH_STORAGE]         = "SPEICHER",
    [TX_SPLASH_SETTINGS]        = "EINSTELLUNGEN",
    [TX_SPLASH_LINK]            = "LINK",
    [TX_SPLASH_IOMCU]           = "KOPROZESSOR",
    [TX_SPLASH_TAGLINE]         = "Prüfstand für Motor, ESC und Servo",
    [TX_SPLASH_CREDIT]          = "erstellt mit Claude Code",

    /* ------------------------------------------------------------ stub */
    [TX_STUB_WHAT]              = "WAS DIESE SEITE KÖNNEN WIRD",
    [TX_STUB_WAITING]           = "WARTET AUF",
    [TX_STUB_CLEAR]             = "NICHTS BLOCKIERT DIESE SEITE",
    [TX_STUB_BUILT]             = "die benötigten Teile sind gebaut und getestet",
    [TX_STUB_MOTOR_1]           = "Throttle: Puls, OneShot, MultiShot, DShot in jeder Rate",
    [TX_STUB_MOTOR_2]           = "Volt, Ampere, Watt, Ladung und Energie, mit Spitzen und Einbruch",
    [TX_STUB_MOTOR_3]           = "Drehzahl von optischem oder magnetischem Geber, Phasenklemme oder ESC",
    [TX_STUB_MOTOR_4]           = "KISS-Telemetrie dekodiert, und Grenzen, die ohne Rückfrage abschalten",
    [TX_STUB_MOTOR_WHY]         = "die Prüfstand-Page ist noch nicht definiert; der Link, der sie trägt, schon",
    [TX_STUB_LOGS_1]            = "Jeden Kanal mit bis zu 1 kHz auf die Karte schreiben",
    [TX_STUB_LOGS_2]            = "Mit Cursorn und Vergleich zurücklesen",
    [TX_STUB_LOGS_3]            = "Einen Lauf als CSV oder Bericht exportieren",
    [TX_STUB_SETUP_1]           = "Akku, Motor, Ausgang, Anschlüsse und Design, in NVS gespeichert",
    [TX_STUB_SETUP_2]           = "Obergrenzen je Buchse: Nieder- und Hochvolt, jeweils in Hardware gesetzt",
    [TX_STUB_SETUP_3]           = "Nur-Signal-Modus je Buchse, Versorgungspin getrennt",
    [TX_STUB_SETUP_4]           = "Profile auf der Karte speichern, vergleichen und wiederherstellen",

    /* ------------------------------------------------------- bus fault */
    [TX_BF_BUS_OFF_TEXT]        = "Panel ist vom Bus getrennt",
    [TX_BF_BUS_REJOIN_TEXT]     = "Panel verbindet sich neu",
    [TX_BF_BUS_STOPPED_TEXT]    = "Controller des Panels steht",
    [TX_BF_BUS_RUNNING_TEXT]    = "Link antwortet nicht mehr",
    [TX_BF_BUS_UNKNOWN_TEXT]    = "Controller nicht lesbar",
    [TX_BF_BUS_REJOIN_WORD]     = "verbindet neu",
    [TX_BF_BUS_STOPPED_WORD]    = "gestoppt",
    [TX_BF_BUS_RUNNING_WORD]    = "läuft",
    [TX_BF_BUS_UNKNOWN_WORD]    = "läuft nicht",
    [TX_BF_BUS_OFF_MEANS]       = "Zu viele Frames unbestätigt; der Controller sendet nicht.",
    [TX_BF_BUS_REJOIN_MEANS]    = "Controller zählt die Ruhezeit zum Neuverbinden. 3 s warten.",
    [TX_BF_BUS_STOPPED_MEANS]   = "Controller steht, nicht neu gestartet: Fehler im Panel.",
    [TX_BF_BUS_RUNNING_MEANS]   = "Controller am Bus, keine Antwort auf seine Frames.",
    [TX_BF_BUS_UNKNOWN_MEANS]   = "Der Treiber läuft nicht, es kann nichts gesendet werden.",
    [TX_BF_REJOIN_1]            = "Das Panel fordert den Bus einmal pro Sekunde zurück.",
    [TX_BF_REJOIN_2]            = "Verschwindet dies von selbst, ist nichts defekt.",
    [TX_BF_REJOIN_3]            = "Bleibt es: Bildschirm fotografieren und melden.",
    [TX_BF_RUNNING_1]           = "Hat der Koprozessor noch Strom? Seine eigene LED.",
    [TX_BF_RUNNING_2]           = "Ein nicht ganz eingerasteter Stecker verhält sich so.",
    [TX_BF_RUNNING_3]           = "Sieht beides richtig aus: Bildschirm fotografieren.",
    [TX_BF_STOPPED_1]           = "Nichts am Prüfstand verursacht das. Es ist ein Fehler",
    [TX_BF_STOPPED_2]           = "  in der Firmware des Panels.",
    [TX_BF_STOPPED_3]           = "Bildschirm fotografieren und melden.",
    [TX_BF_SILENT_MEANS]        = "Am Bus hat niemand geantwortet. Die Platinen reden nicht.",
    [TX_BF_CORRUPT_MEANS]       = "Frames kommen verändert an. Leitung oder Bit-Timing.",
    [TX_BF_LOSSY_MEANS]         = "Frames gehen teils verloren, der Bus meldet Fehler.",
    [TX_BF_DROPPED_MEANS]       = "Frames kamen intakt, blieben ungelesen. Nicht die Leitung.",
    [TX_BF_SILENT_1]            = "Koprozessor versorgt? Seine LED, nicht die des Panels.",
    [TX_BF_SILENT_2]            = "CANH an CANH und CANL an CANL, nicht vertauscht.",
    [TX_BF_SILENT_3]            = "Beide Platinen mit demselben Release geflasht.",
    [TX_BF_SILENT_4]            = "Abschlüsse: etwa 60 Ohm zwischen CANH und CANL,",
    [TX_BF_SILENT_5]            = "  gemessen bei ausgeschaltetem Prüfstand.",
    [TX_BF_CORRUPT_1]           = "Abschlüsse: etwa 60 Ohm zwischen CANH und CANL bei",
    [TX_BF_CORRUPT_2]           = "  ausgeschaltetem Prüfstand. 120 Ohm: einer fehlt.",
    [TX_BF_CORRUPT_3]           = "Stichleitung zu jeder Platine unter 30 cm halten.",
    [TX_BF_TWISTED]             = "CANH und CANL verdrillt, fern von Motorleitungen.",
    [TX_BF_LOSSY_1]             = "Abschlüsse: ca. 60 Ohm CANH-CANL, Prüfstand aus.",
    [TX_BF_LOSSY_2]             = "Bus gesamt unter 5 m, jede Stichleitung unter 30 cm.",
    [TX_BF_LOSSY_4]             = "Ein nicht ganz eingerasteter Stecker verhält sich so.",
    [TX_BF_DROPPED_1]           = "Die Verkabelung ist es nicht: Frames kamen intakt an.",
    [TX_BF_DROPPED_2]           = "Etwas las sie nicht rechtzeitig. Bitte melden,",
    [TX_BF_DROPPED_3]           = "  mit den Zahlen rechts.",
    [TX_BF_HEAD_MEANS]          = "WAS DAS BEDEUTET",
    [TX_BF_HEAD_CHECK]          = "PRÜFEN, IN DIESER REIHENFOLGE",
    [TX_BF_NOTE_1]              = "Quittieren lässt den Prüfstand in der Simulation. Er zeigt",
    [TX_BF_NOTE_2]              = "Zahlen, und nichts steuert einen Ausgang an.",
    [TX_BF_NOTE_LOST]           = "Dieselben Zahlen stehen in RCBENCH.LOG auf der Karte.",
    [TX_BF_NOTE_TEST]           = "Der Test läuft bei jedem Start erneut.",
    [TX_BF_ACKNOWLEDGED]        = "QUITTIERT",
    [TX_BF_HOLD]                = "2 s HALTEN ZUM QUITTIEREN",
    [TX_BF_THIS_PANEL]          = "DIESES PANEL",
    [TX_BF_DOWN]                = "getrennt      %lu s",
    [TX_BF_REQUESTS]            = "Anfragen      %lu",
    [TX_BF_NO_ANSWER]           = "unbeantwortet %lu",
    [TX_BF_REJOINS]             = "Neuverbindungen %lu",
    [TX_BF_MEASURED]            = "GEMESSEN",
    [TX_BF_SENT]                = "gesendet   %lu",
    [TX_BF_RETURNED]            = "zurück     %lu",
    [TX_BF_ALTERED]             = "verändert  %lu",
    [TX_BF_LOST]                = "verloren   %lu",
    [TX_BF_COPROCESSOR]         = "KOPROZESSOR",
    [TX_BF_NO_REPLY]            = "antwortete nicht",
    [TX_BF_CAN_UP]              = "CAN aktiv",
    [TX_BF_CAN_DOWN]            = "CAN INAKTIV",
    [TX_BF_DROPPED]             = "verworfen %u",

    /* --------------------- CAN self-test verdicts, in the heading face */
    [TX_CAN_OK]                 = "alle Testframes intakt zurück",
    [TX_CAN_SILENT]             = "kein Testframe kam zurück",
    [TX_CAN_CORRUPT]            = "Testframes verändert zurück",
    [TX_CAN_LOSSY]              = "Testframes gehen verloren",
    [TX_CAN_DROPPED]            = "Testframes weg ohne Busfehler",
    [TX_CAN_RUNNING]            = "läuft",

    /* --------------------------------------------------------- outputs */
    [TX_OUT_PROTOCOL]           = "PROTOKOLL",
    [TX_OUT_PINS_OF]            = "%u VON %u PINS",
    [TX_OUT_CHANNELS_ON_PIN]    = "%u KANÄLE AUF EINEM PIN",
    [TX_OUT_TAKES_PIN]          = "%s BELEGT %u PIN",
    [TX_OUT_TAKES_PINS]         = "%s BELEGT %u PINS",
    [TX_OUT_ALL_SLOTS]          = "ALLE %u SLOTS BELEGT",
    [TX_OUT_NEEDS_CHANNEL]      = "BRAUCHT %u KANAL, %u FREI",
    [TX_OUT_NEEDS_CHANNELS]     = "BRAUCHT %u KANÄLE, %u FREI",
    [TX_OUT_LAST_WRITE]         = "LETZTER SCHREIBVORGANG",
    [TX_OUT_WRITTEN]            = "GESCHRIEBEN",
    [TX_OUT_REFUSED]            = "ABGELEHNT",
    [TX_OUT_NOT_WRITTEN]        = "NICHT GESCHR.",
    [TX_OUT_NO_LINK]            = "KEIN LINK",
    [TX_OUT_OFF_VIEW]           = "OFF ZEIGT ALLES, ÄNDERT NICHTS",
    [TX_OUT_NOT_READ]           = "BINDUNG NICHT GELESEN - GESPERRT",
    [TX_OUT_NOT_MAPPED]         = "PAGES OHNE GÜLTIGE BINDUNG",
    [TX_OUT_HOLD_UNBIND]        = "HALTEN: ALLE PINS LÖSEN",
    [TX_PK_NOT_READ]            = "NICHT GELESEN",

    /* ------------------------------------------------------ pin picker */
    [TX_PK_NONE_YET]            = "NOCH KEINE",
    [TX_PK_IN_USE]              = "BELEGT",
    [TX_PK_BY_OTHERS]           = "VON ANDEREN",
    [TX_PK_NONE]                = "KEINE",
    [TX_PK_NO_ART_1]            = "KEIN BILD DIESER PLATINE",
    [TX_PK_NO_ART_2]            = "SIE GIBT NICHT AN, WO IHRE PADS LIEGEN,",
    [TX_PK_NO_ART_3]            = "EINE ZEICHNUNG WÄRE DAHER GERATEN.",
    [TX_PK_NO_ART_4]            = "IHRE PINS STEHEN AUF DER SEITE OUTPUTS.",

    /* -------------------------------------------------------- analyser */
    [TX_AN_TAB_CHANNELS]        = "KANÄLE",
    [TX_AN_TAB_RAW]             = "ROH",
    [TX_AN_LAST_FRAME]          = "LETZTER FRAME",
    [TX_AN_NOTHING_YET]         = "noch nichts dekodiert",
    [TX_AN_BYTES]               = "%u Bytes, getrennt an einer Pause von %u us",
    [TX_AN_SILENT]              = "SILENT",
    [TX_AN_LIVE]                = "LIVE",
    [TX_AN_WHY_SILENT]          = "Leitung still",
    [TX_AN_WHY_FAILSAFE]        = "Werte sind erfunden",
    [TX_AN_WHY_LOST]            = "Frame kam defekt an",
    [TX_AN_WHY_LIVE]            = "Sender empfangen",

    /* --------------------------------------------------------- battery */
    [TX_BAT_NO_MONITOR]         = "kein Monitor am Balancer-Anschluss",
    [TX_BAT_NO_PACK]            = "KEIN AKKU",
    [TX_BAT_NO_PACK_WHY]        = "nichts am Balancer-Anschluss",
    [TX_BAT_REPLACE]            = "ERSETZEN",
    [TX_BAT_REPLACE_WHY]        = "eine Zelle weicht ab",
    [TX_BAT_WATCH]              = "BEOBACHTEN",
    [TX_BAT_WATCH_WHY]          = "die Streuung wächst",
    [TX_BAT_HEALTHY]            = "GUT",
    [TX_BAT_HEALTHY_WHY]        = "Zellen gleich unter Last",
    [TX_BAT_CELLS]              = "ZELLEN",
    [TX_BAT_PACK]               = "AKKU",
    [TX_BAT_MEAN]               = "MITTEL",
    [TX_BAT_SPREAD]             = "STREUUNG",
    [TX_BAT_PACK_IR]            = "AKKU iR",
    [TX_BAT_USED]               = "ENTNOMMEN",
    [TX_BAT_USED_OF]            = "%d von %d mAh",
    [TX_BAT_NOTE_1]             = "Die Streuung gilt unter Last.",
    [TX_BAT_NOTE_2]             = "In Ruhe sieht eine müde Zelle",
    [TX_BAT_NOTE_3]             = "wie jede andere aus.",
    [TX_BAT_DIVERGENCE]         = "ZELLENABWEICHUNG",

    /* --------------------------------------------------------- balance */
    [TX_BAL_TAB_BALANCE]        = "WUCHTEN",
    [TX_BAL_TAB_RIG]            = "TESTGESTELL",
    [TX_BAL_TAB_AIRCRAFT]       = "FLUGMODELL",
    [TX_BAL_ACCELEROMETER]      = "BESCHLEUNIGUNGSSENSOR",
    [TX_BAL_ONE_MARK]           = "EINE MARKE",
    [TX_BAL_OPTICAL]            = "OPTISCH",
    [TX_BAL_FIREWALL]           = "MOTORSPANT",
    [TX_BAL_TIED_DOWN]          = "FESTGEBUNDEN",
    [TX_BAL_RIG_1]              = "QUER ZUR WELLE",
    [TX_BAL_RIG_1A]             = "Eine Unwucht zieht seitlich,",
    [TX_BAL_RIG_1B]             = "nicht in Wellenrichtung.",
    [TX_BAL_RIG_2]              = "SO NAH WIE MÖGLICH",
    [TX_BAL_RIG_2A]             = "Jede Fuge vor dem Sensor ist",
    [TX_BAL_RIG_2B]             = "eine ungewollte Feder.",
    [TX_BAL_RIG_3]              = "VERSCHRAUBT, NICHT GEKLEBT",
    [TX_BAL_RIG_3A]             = "Schaum schluckt genau die",
    [TX_BAL_RIG_3B]             = "Frequenzen, die zählen.",
    [TX_BAL_RIG_4]              = "EINE MARKE PRO UMDREHUNG",
    [TX_BAL_RIG_4A]             = "Auf die Glocke. Ein Blatt",
    [TX_BAL_RIG_4B]             = "gibt einen Puls je Blatt.",
    [TX_BAL_RIG_5]              = "STIFT, NICHT KLEBEBAND",
    [TX_BAL_RIG_5A]             = "Alles Aufgeklebte ist Masse,",
    [TX_BAL_RIG_5B]             = "die dann mitgemessen wird.",
    [TX_BAL_RIG_6]              = "RAUS AUS DEM LUFTSTROM",
    [TX_BAL_RIG_6A]             = "Ein flatterndes Kabel ist",
    [TX_BAL_RIG_6B]             = "ein zweiter Sensor.",
    [TX_BAL_AIR_1]              = "MOTORSPANT, NICHT HAUBE",
    [TX_BAL_AIR_1A]             = "Eine Haube ist Verkleidung.",
    [TX_BAL_AIR_1B]             = "Sie bewegt sich gegen alles.",
    [TX_BAL_AIR_2]              = "FLACH GEHT",
    [TX_BAL_AIR_2A]             = "Flach montieren, eine Achse",
    [TX_BAL_AIR_2B]             = "in der Spantebene nehmen.",
    [TX_BAL_AIR_3]              = "NAHE DEN SCHRAUBEN",
    [TX_BAL_AIR_3A]             = "Wie am Gestell: Fugen",
    [TX_BAL_AIR_3B]             = "zwischen Sensor und Lager.",
    [TX_BAL_AIR_4]              = "WEITER DIE GLOCKE",
    [TX_BAL_AIR_4A]             = "Ein Spinner kommt ab und",
    [TX_BAL_AIR_4B]             = "neu im anderen Winkel drauf.",
    [TX_BAL_AIR_5]              = "HECK FESTBINDEN",
    [TX_BAL_AIR_5A]             = "Ein Modell, das schaukelt,",
    [TX_BAL_AIR_5B]             = "ist eine ungewollte Feder.",
    [TX_BAL_AIR_6]              = "KABEL AUS DEM LUFTSTROM",
    [TX_BAL_AIR_6A]             = "Und fixiert: ein loses Kabel",
    [TX_BAL_AIR_6B]             = "ist ein zweiter Sensor.",
    [TX_BAL_WRONG]              = "TYPISCHE FEHLER",
    [TX_BAL_BLADES]             = "BLÄTTER",
    [TX_BAL_VIBRATION]          = "VIBRATION",
    [TX_BAL_ANGLE]              = "WINKEL",
    [TX_BAL_ADD]                = "ZUFÜGEN",
    [TX_BAL_WHERE]              = "WO",
    [TX_BAL_HUB]                = "Nabe, %d deg",
    [TX_BAL_BETWEEN]            = "zwischen %d und %d",
    [TX_BAL_NOTE_1]             = "Vier Läufe: Referenz, dann je",
    [TX_BAL_NOTE_2]             = "eine Testmasse bei 0, 120, 240.",
    [TX_BAL_NOTE_3]             = "Ein Indexpuls halbiert das.",

    /* ----------------------------------------------------------- SETUP */
    [TX_SET_COUNT]              = "%d EINSTELLUNGEN",
    [TX_SET_PINS_CAPTION]       = "PINS: LISTE ODER PLATINE",
    [TX_SET_RESET]              = "KATEGORIE ZURÜCKSETZEN",
    [TX_SET_SAVED]              = "GESPEICHERT",
    [TX_SET_WHEN_IDLE]          = "BEI STILLSTAND",
    [TX_SET_NOT_SAVED]          = "NICHT GESPEICHERT",
    [TX_SET_SAVE]               = "SPEICHERN",
    [TX_SET_UNHELD]             = "Vom Koprozessor nicht übernommen",

    /* -------------------------------------------- plots and hero cards */
    [TX_PLOT_NOW]               = "JETZT",
    [TX_PLOT_END]               = "ENDE",
    [TX_HERO_PEAK]              = "max",
    [TX_HERO_MIN]               = "min",

    /* ----------------------------------------------------- MOTOR & ESC */
    [TX_MO_VOLT]                = "SPANN.",
    [TX_MO_CURR]                = "STROM",
    [TX_MO_PWR]                 = "LEIST.",
    [TX_MO_RPM]                 = "RPM",
    [TX_MO_TAB_PLOT]            = "GRAFIK",
    [TX_MO_TAB_TABLE]           = "TABELLE",
    [TX_MO_RATE_ERR]            = "%d Hz   FEHLER %lu",
    [TX_MO_TABLE_HEAD]          = "KANAL          JETZT          SPITZE",
    [TX_MO_ROW_VOLTAGE]         = "SPANNUNG",
    [TX_MO_ROW_CURRENT]         = "STROM",
    [TX_MO_ROW_POWER]           = "LEISTUNG",
    [TX_MO_ROW_RPM]             = "RPM",
    [TX_MO_TABLE_MAX]           = "max",
    [TX_MO_TABLE_DIFF]          = "Abw.",
    [TX_MO_TABLE_CLIPPED]       = "ÜBERSTEUERT",
    [TX_MO_ESC_SAYS]            = "ESC MELDET",
    [TX_MO_TAG_LIVE]            = "TELEMETRIE LIVE",
    [TX_MO_TAG_HELD]            = "LETZTER LAUF",
    [TX_MO_TAG_IDLE]            = "TELEMETRIE RUHT",
    [TX_MO_CONTROL]             = "STEUERUNG",
    [TX_MO_NO_RUN]              = "kein Lauf aufgezeichnet",
    [TX_MO_HINT]                = "BALKEN ZIEHEN ODER AN DEN ENDEN UM EINEN PUNKT ÄNDERN",
    [TX_MO_RESET_PEAKS]         = "SPITZEN ZURÜCKSETZEN",

    /* ---------------------------------------------------------- SUPPLY */
    [TX_SUP_ROW_V_MAX]          = "SPANNUNG MAX",
    [TX_SUP_ROW_I_MAX]          = "STROM MAX",
    [TX_SUP_ROW_V_START]        = "STARTSPANNUNG",
    [TX_SUP_ROW_I_START]        = "STARTSTROM",
    [TX_SUP_ROW_TRIP_I]         = "ÜBERSTROM",
    [TX_SUP_ROW_TRIP_V]         = "ÜBERSPANNUNG",
    [TX_SUP_ROW_TRIP_MS]        = "ABSCHALTZEIT",
    [TX_SUP_ROW_CONFIRM_SLIDE]  = "SLIDER, SCHRITTE",
    [TX_SUP_ROW_CONFIRM_KEYS]   = "TASTENFELD",
    [TX_SUP_VOLTAGE]            = "SPANNUNG",
    [TX_SUP_CURRENT_LIMIT]      = "STROMBEGRENZUNG",
    [TX_SUP_OUTPUT_ON]          = "AUSGANG EIN",
    [TX_SUP_OUTPUT_OFF]         = "AUSGANG AUS",
    [TX_SUP_MODE_TRIP]          = "ABSCH.",
    [TX_SUP_MODE_OFF]           = "AUS",
    [TX_SUP_LINE_TRIP_I]        = "Überstrom",
    [TX_SUP_LINE_TRIP_V]        = "Überspannung",
    [TX_SUP_LINE_CC]            = "an der Grenze",
    [TX_SUP_LINE_CV]            = "an der Spannung",
    [TX_SUP_MODEL]              = "NETZTEIL SIMULIERT",
    [TX_SUP_ONLINE]             = "ONLINE",
    [TX_SUP_NOT_ANSWERING]      = "ANTWORTET NICHT",
    [TX_SUP_SETTINGS]           = "OPTIONEN",
    [TX_SUP_MODE]               = "MODUS",
    [TX_SUP_TABLE_HEAD]         = "KANAL          SOLL           JETZT",
    [TX_SUP_OV_TITLE]           = "NETZTEIL-OPTIONEN",
    [TX_SUP_CLOSE]              = "SCHLIESSEN",
    [TX_SUP_RESET_PDMINI]       = "PD MINI ZURÜCKSETZEN",
    [TX_SUP_CAPS]               = "OBERGRENZEN",
    [TX_SUP_AFTER_RESTART]      = "NACH NEUSTART",
    [TX_SUP_TRIPS]              = "ABSCHALTUNGEN",
    [TX_SUP_CONFIRM_ON]         = "RÜCKFRAGE IM BETRIEB",
    [TX_SUP_HELP_1]             = "Eine Abschaltung schaltet den",
    [TX_SUP_HELP_2]             = "Ausgang aus, wenn Messwerte die",
    [TX_SUP_HELP_3]             = "Abschaltzeit lang darüber liegen.",
    [TX_SUP_SAVED]              = "GESPEICHERT",
    [TX_SUP_SAVE_WAITING]       = "SPEICHERN WARTET",
    [TX_SUP_NOT_SAVED]          = "NICHT GESPEICHERT",
    [TX_SUP_SETUP_NOT_SAVED]    = "ÄNDERUNGEN IN SETUP NICHT GESPEICHERT",
    [TX_SUP_OUTPUT_IS_ON]       = "AUSGANG IST EIN",
    [TX_SUP_ASK_WHY]            = "Ein neuer Sollwert wirkt sofort auf die Last.",
    [TX_SUP_APPLY]              = "ÜBERNEHMEN",
    [TX_SUP_ASK_OFF]            = "OPTIONEN, RÜCKFRAGE IM BETRIEB, schaltet diese Rückfrage ab.",
    [TX_SUP_TAG_LIVE]           = "AUSGANG LIVE",
    [TX_SUP_TAG_HELD]           = "AUSGANG, LETZTER LAUF",
    [TX_SUP_TAG_IDLE]           = "AUSGANG RUHT",
    [TX_SUP_SET_POINTS]         = "SOLLWERTE",
    [TX_SUP_NOT_ON_YET]         = "Ausgang noch nicht eingeschaltet",

    /* ------------------------------------------------------ LOG VIEWER */
    [TX_LOG_NO_SOURCE]          = "keine Dateiquelle",
    [TX_LOG_CANNOT_OPEN]        = "kann %s nicht öffnen",
    [TX_LOG_IS_FOLDER]          = "%s ist ein Ordner",
    [TX_LOG_CANNOT_DELETE]      = "kann %s nicht löschen",
    [TX_LOG_DELETED]            = "%s gelöscht",
    [TX_LOG_ERR_OK]             = "ok",
    [TX_LOG_ERR_READ]           = "Datei nicht lesbar",
    [TX_LOG_ERR_NO_HEADER]      = "keine Kopfzeile",
    [TX_LOG_ERR_NO_ROWS]        = "keine Datenzeilen unter der Kopfzeile",
    [TX_LOG_ERR_NO_NUMERIC]     = "keine Zahlenspalten -- Trennzeichen prüfen",
    [TX_LOG_ERR_COLUMNS]        = "zu viele Spalten",
    [TX_LOG_ERR_MEMORY]         = "kein Speicher frei",
    [TX_LOG_ERR_ARG]            = "ungültiges Argument",
    [TX_LOG_ERR_UNKNOWN]        = "unbekannter Fehler",
    [TX_LOG_DELETE_TITLE]       = "VON KARTE LÖSCHEN",
    [TX_LOG_DELETE_WHAT]        = "Die Datei wird von der Karte entfernt.",
    [TX_LOG_DELETE_FINAL]       = "Das lässt sich nicht rückgängig machen.",
    [TX_LOG_DELETE]             = "LÖSCHEN",
    [TX_LOG_SD_CARD]            = "SD-KARTE",
    [TX_LOG_NO_LOGS]            = "KEINE LOGS",
    [TX_LOG_NO_CARD]            = "Keine Karte. Karte einsetzen und NEU LESEN tippen.",
    [TX_LOG_NO_CSV]             = "Keine .csv-Dateien im Hauptverzeichnis.",
    [TX_LOG_RUNS_HERE]          = "Läufe landen hier als BENCH001.CSV und aufwärts.",
    [TX_LOG_N_OF_FILES]         = "%d VON %d DATEIEN",
    [TX_LOG_FILES]              = "DATEIEN",
    [TX_LOG_DIR]                = "ORDNER",
    [TX_LOG_RESCAN]             = "NEU LESEN",
    [TX_LOG_OPEN]               = "ÖFFNEN",
    [TX_LOG_CANNOT_READ]        = "NICHT LESBAR",
    [TX_LOG_UNREADABLE]         = "nicht lesbar",
    [TX_LOG_TRY_ANOTHER]        = "Unten ein anderes Trennzeichen oder eine andere Datei wählen.",
    [TX_LOG_DETECTED]           = "ERKANNT",
    [TX_LOG_KEY_SEPARATOR]      = "TRENNER",
    [TX_LOG_KEY_NUMBERS]        = "ZAHLEN",
    [TX_LOG_KEY_ROWS]           = "ZEILEN",
    [TX_LOG_KEY_COLUMNS]        = "SPALTEN",
    [TX_LOG_KEY_TIME]           = "ZEITACHSE",
    [TX_LOG_KEY_RAGGED]         = "UNGLEICH",
    [TX_LOG_SEMICOLON]          = "SEMIKOLON",
    [TX_LOG_COMMA]              = "KOMMA",
    [TX_LOG_TAB]                = "TAB",
    [TX_LOG_PIPE]               = "PIPE",
    [TX_LOG_GERMAN]             = "DEUTSCH",
    [TX_LOG_ENGLISH]            = "ENGLISCH",
    [TX_LOG_SET]                = "(GESETZT)",
    [TX_LOG_CAPPED]             = "(BEGRENZT)",
    [TX_LOG_ROW_INDEX]          = "ZEILENINDEX",
    [TX_LOG_PLUS_LONG]          = "+LANG",
    [TX_LOG_EVIDENCE]           = "BELEGE  de %d  en %d  unklar %d",
    [TX_LOG_MIXED]              = "BEIDES BELEGT - DATEI GEMISCHT",
    [TX_LOG_TOO_LONG]           = "%d ZEILE(N) ZU LANG, REST FEHLT",
    [TX_LOG_ROWS_DIFFER]        = "ZEILEN UNGLEICH: TRENNER FALSCH?",
    [TX_LOG_UNSETTLED]          = "NICHT EINDEUTIG - UNTEN PRÜFEN",
    [TX_LOG_HINT_NUM]           = "WERTE FALSCH?  ZAHLEN ÄNDERN",
    [TX_LOG_HINT_SEP]           = "SPALTEN FALSCH?  TRENNER ÄNDERN",
    [TX_LOG_PLOT_N]             = "GRAFIK  %d/%d",
    [TX_LOG_TIME]               = "ZEIT",
    [TX_LOG_TEXT]               = "TEXT",
    [TX_LOG_BTN_SEP]            = "TRENNER %s",
    [TX_LOG_BTN_NUM]            = "ZAHLEN %s",
    [TX_LOG_BACK]               = "ZURÜCK",
    [TX_LOG_PLOT]               = "GRAFIK",
    [TX_LOG_NOTHING_LOADED]     = "NICHTS GELADEN",
    [TX_LOG_PICK_FIRST]         = "Zuerst eine Datei wählen.",
    [TX_LOG_SUMMARY]            = "%s   %d ZEILEN   %.2f s   %.0f Hz",
    [TX_LOG_AT_TIME]            = "t = %.3f s   Messpunkt %d/%d",
    [TX_LOG_AT_ROW]             = "Zeile %d von %d   (keine Zeitspalte)",
    [TX_LOG_UNREADABLE_CELLS]   = "%d ZELLEN UNLESBAR",

    /* ------------------------------------------------------ PROGRAMMER */
    [TX_PG_BLURB_ESC]           = "Bootloader, CLI und Pakete",
    [TX_PG_BLURB_SERVO]         = "Servos, offene Protokolle",
    [TX_PG_BLURB_STICK]         = "Throttle-Menüs, Pieptöne",
    [TX_PG_GROUP_MOTOR]         = "MOTOR",
    [TX_PG_GROUP_STARTUP]       = "ANLAUF",
    [TX_PG_GROUP_PROTECTION]    = "SCHUTZ",
    [TX_PG_GROUP_SOUND]         = "TON",
    [TX_PG_GROUP_TRAVEL]        = "WEG",
    [TX_PG_GROUP_RESPONSE]      = "VERHALTEN",
    [TX_PG_GROUP_REPORTING]     = "MELDUNG",
    [TX_PG_HELP_DIRECTION]      = "Drehrichtung, und ob Rückwärts überhaupt erlaubt ist",
    [TX_PG_HELP_TIMING_STEPS]   = "Wie weit vor dem Rotor kommutiert wird: mehr passt zu hohem kV",
    [TX_PG_HELP_PWM]            = "Höher ist leiser und wärmer; niedriger ist effizient und hörbar",
    [TX_PG_HELP_STARTUP]        = "Wie kräftig er anschiebt, bevor er den Rotor erkennt",
    [TX_PG_HELP_DEMAG]          = "Nimmt zurück, wenn das Feld spät zusammenbricht: hilft gegen Blockieren unter Last",
    [TX_PG_HELP_BRAKE]          = "Hält den Motor bei null Throttle fest, statt ihn auslaufen zu lassen",
    [TX_PG_HELP_LVC]            = "Je Zelle: ab hier wird Leistung zurückgenommen, um den Akku zu schonen",
    [TX_PG_HELP_BEEP]           = "Lautstärke der Starttöne und des Pieptons bei Signalverlust",
    [TX_PG_HELP_TIMING_DEG]     = "Grad vor dem Rotor: mehr gibt Drehzahl und Wärme, weniger ist kühler",
    [TX_PG_HELP_SINE]           = "Treibt eine Sinuswelle, bis die Drehzahl zum Erkennen des Rotors reicht",
    [TX_PG_HELP_COMPLEMENTARY]  = "Treibt beide Brückenhälften: kühler, braucht aber sauberes Timing",
    [TX_PG_HELP_TELEMETRY]      = "Sendet Volt, Ampere und Drehzahl über die Signalleitung zurück",
    [TX_PG_HELP_MOTOR_TYPE]     = "Sechsschritt-Kommutierung oder feldorientierte Regelung",
    [TX_PG_HELP_CURRENT]        = "Höchster Strom durch den Motor, gleich was gefordert wird",
    [TX_PG_HELP_REGEN]          = "Bremsenergie geht zurück in den Akku statt in den Motor",
    [TX_PG_HELP_CENTRE]         = "Lage von Centre, in Mikrosekunden um 1500",
    [TX_PG_HELP_ENDPOINT]       = "Wie weit er von Centre aus in jede Richtung darf",
    [TX_PG_HELP_HORN]           = "In welche Richtung das Ruderhorn bei steigendem Puls läuft",
    [TX_PG_HELP_SPEED]          = "Bewegt das Ruderhorn bewusst langsam, für Scale-Modelle und weiche Anlenkungen",
    [TX_PG_HELP_DEADBAND]       = "Abweichung, die er vor dem Nachregeln duldet: breiter läuft kühler",
    [TX_PG_HELP_RESOLUTION]     = "Wie fein er die befohlene Position auflöst",
    [TX_PG_HELP_OVERLOAD]       = "Nimmt zurück, wenn er so lange blockiert, dass er überhitzen würde",
    [TX_PG_HELP_FAILSAFE]       = "Fährt ohne Puls auf eine feste Position, statt kraftlos zu werden",
    [TX_PG_TRANSPORT_ONEWIRE]   = "Eindraht-Bootloader, 19200 Baud",
    [TX_PG_TRANSPORT_CLI]       = "Text-CLI über die Signalleitung",
    [TX_PG_TRANSPORT_PACKETS]   = "Pakete mit Rahmen, 115200 Baud",
    [TX_PG_TRANSPORT_HITEC]     = "Servoprotokoll der D-Serie",
    [TX_PG_DEVICE_BLHELI]       = "BLHeli_S 16.7  auf  EFM8BB21",
    [TX_PG_DEVICE_AM32]         = "AM32 2.15  auf  STM32G071",
    [TX_PG_DEVICE_ESCAPE32]     = "ESCape32 v9  auf  AT32F421",
    [TX_PG_DEVICE_VESC]         = "VESC 6.05  auf  STM32F405",
    [TX_PG_PROFILES_RUN]        = "%d von %d Profilen ausführbar",
    [TX_PG_PROTOCOL]            = "%d Protokoll",
    [TX_PG_PROTOCOLS]           = "%d Protokolle",
    [TX_PG_WHAT]                = "WAS WIRD PROGRAMMIERT?",
    [TX_PG_NOTHING_ANSWERED]    = "nichts hat geantwortet",
    [TX_PG_CONNECT]             = "VERBINDEN",
    [TX_PG_DISCONNECT]          = "TRENNEN",
    [TX_PG_PARAMETERS]          = "PARAMETER",
    [TX_PG_NO_DEVICE]           = "kein Gerät, daher nichts anzuzeigen",
    [TX_PG_RANGE_OF]            = "%d-%d von %d",
    [TX_PG_WRITE_N]             = "SCHREIBEN %d",
    [TX_PG_WRITE]               = "SCHREIBEN",
    [TX_PG_READ]                = "LESEN",

    /* ------------------------------------------------------- ESC STICK */
    [TX_SP_NEEDS_V]             = "%u.%u V, Obergrenze %u.%u V",
    [TX_SP_AT_MOST]             = "höchstens %u Änderungen pro Lauf",
    [TX_SP_NO_CELLS]            = "keine Zellenzahl im Profil: SPANNUNG unter TIMING setzen",
    [TX_SP_ABOVE_CAP]           = "%u.%02u V über der SUPPLY-Obergrenze von %u.%02u V",
    [TX_SP_BELOW_MIN]           = "SPANNUNG unter den %u.%02u V des Netzteils",
    [TX_SP_ITEM_NOT_HERE]       = "%u %s gibt es an diesem Modell nicht",
    [TX_SP_V_OVER_ESC]          = "%u.%u V, ESC bis %u.%u V",
    [TX_SP_V_OVER_ESC_NOTE]     = "SPANNUNG %u.%u V liegt über den %u.%u V des ESC",
    [TX_SP_V_CELLS_OVER_ESC_NOTE] = "%u.%u V der Zellenzahl liegen über den %u.%u V des ESC",
    [TX_SP_V_UNRATED]           = "ESC-Grenze unbekannt",
    [TX_SP_V_UNRATED_CELLS_NOTE] = "%u.%u V nach Zellenzahl der Familie: Grenze unbekannt",
    [TX_SP_V_UNRATED_NOTE]      = "SPANNUNG %u.%u V: ESC-Grenze unbekannt, prüfen",
    [TX_SP_V_UNDER_ESC]         = "%u.%u V, ESC ab %u.%u V",
    [TX_SP_V_UNDER_ESC_NOTE]    = "SPANNUNG %u.%u V liegt unter den %u.%u V des ESC",
    [TX_SP_I_OVER_ESC]          = "%u.%u A, ESC bis %u A",
    [TX_SP_I_OVER_ESC_NOTE]     = "STROMBEGRENZUNG %u.%u A liegt über den %u A des ESC",
    [TX_SP_I_ABOVE_CAP]         = "STROMBEGRENZUNG über SUPPLY-Obergrenze von %u.%02u A",
    [TX_SP_SUPPLY_NOT_OFF]      = "kein frischer Messwert meldet das Netzteil aus",
    [TX_SP_OUTPUT_LIVE]         = "zuerst den Ausgang des Netzteils ausschalten",
    [TX_SP_REFUSED]             = "abgelehnt",
    [TX_SP_LIST_COUNT]          = "%d-%d von %d, %d ausführbar",
    [TX_SP_LIST_FOUND]          = "%d-%d/%d gefunden, %d ausführbar",
    [TX_SP_MAKERS_COUNT]        = "%d-%d/%d Hersteller, %d ausführbar",
    [TX_SP_MAKERS_FOUND]        = "%d-%d/%d Hersteller, %d ausführbar",
    [TX_SP_MAKER_MODELS]        = "%u VON %u AUSFÜHRBAR",
    [TX_SP_MAKER_FOUND]         = "%u VON %u GEFUNDEN, %u AUSFÜHRBAR",
    [TX_SP_FIND]                = "SUCHE",
    [TX_SP_FIND_TITLE]          = "SUCHE  * = beliebiger Text",
    [TX_SP_FIND_NONE]           = "Kein Profil passt zur Suche.",
    [TX_SP_CARD]                = "KARTE",
    [TX_SP_ITEM]                = "%u PUNKT",
    [TX_SP_ITEMS]               = "%u PUNKTE",
    [TX_SP_TWO_STAGE]           = "ZWEISTUFIG",
    [TX_SP_ONE_STAGE]           = "EINSTUFIG",
    [TX_SP_UNVERIFIED_ALL]      = "Kein Profil ist geprüft: kein ESC wurde aufgezeichnet.",
    [TX_SP_WHY_STOP]            = "STOP wurde gedrückt.",
    [TX_SP_WHY_BENCH_STOP]      = "Der Prüfstand hat selbst gestoppt: Touch oder Koprozessor. Das Band sagt, warum.",
    [TX_SP_WHY_DISARMED]        = "Der Prüfstand war während des Laufs DISARMED.",
    [TX_SP_WHY_LINK]            = "Der Koprozessor antwortet nicht mehr.",
    [TX_SP_WHY_SUPPLY_OFF]      = "Der Ausgang des Netzteils ging aus: Abschaltung oder verlorenes EIN.",
    [TX_SP_WHY_SUPPLY_LOST]     = "Das Netzteil antwortet nicht mehr.",
    [TX_SP_WHY_STALE]           = "Kein neuer Messwert des Netzteils seit 1000 ms.",
    [TX_SP_WHY_RATE]            = "3 Messwerte nacheinander kamen später als PIEPTON MIN oder PAUSE MIN.",
    [TX_SP_WHY_NOT_ARMED]       = "Der Prüfstand war nach 3000 ms nicht ARMED.",
    [TX_SP_WHY_NO_POWER]        = "Das Netzteil meldete den Ausgang nicht binnen 3000 ms als EIN.",
    [TX_SP_WHY_NO_BEEPS]        = "Kein Piepton für STILLE: Last und SCHWELLE prüfen.",
    [TX_SP_WHY_HIGH]            = "Der Strom blieb über SCHWELLE: ein laufender Motor, oder SCHWELLE zu niedrig.",
    [TX_SP_WHY_TIMEOUT]         = "Die gesuchten Pieptöne kamen nicht in Folge innerhalb ZEITLIMIT.",
    [TX_SP_WHY_HAND]            = "Kein ERLEDIGT für den Handgriff innerhalb %u s.",
    [TX_SP_WHY_SUPPLY_ON]       = "Das Netzteil meldete den Ausgang nicht binnen 3000 ms als AUS.",
    [TX_SP_WHY_TOUCH]           = "Touch-Ereignisse gingen verloren, bevor ARM galt.",
    [TX_SP_WHY_USER]            = "ABBRECHEN wurde gedrückt.",
    [TX_SP_WHY_LEFT]            = "Die Seite wurde während des Laufs verlassen.",
    [TX_SP_PH_READY]            = "BEREIT",
    [TX_SP_PH_ARMING]           = "ARMING",
    [TX_SP_PH_SIGNAL]           = "SIGNAL",
    [TX_SP_PH_POWER]            = "EINSCHALTEN",
    [TX_SP_PH_ENTRY]            = "EINSTIEG",
    [TX_SP_PH_ITEMS]            = "PUNKTE",
    [TX_SP_PH_VALUES]           = "WERTE",
    [TX_SP_PH_STORE]            = "SPEICHERN",
    [TX_SP_PH_CYCLE]            = "AUS UND EIN",
    [TX_SP_PH_HAND_OFF]         = "HANDGRIFF",
    [TX_SP_PH_HAND_ON]          = "HANDGRIFF, VERSORGT",
    [TX_SP_PH_HAND_END]         = "WARTEN AUF DEN ESC",
    [TX_SP_PH_OFF]              = "AUSSCHALTEN",
    [TX_SP_PH_DONE]             = "FERTIG",
    [TX_SP_PH_ABORTED]          = "ABGEBROCHEN",
    [TX_SP_R_STOP]              = "STOP",
    [TX_SP_R_BENCH_STOP]        = "PRÜFSTAND GESTOPPT",
    [TX_SP_R_DISARMED]          = "DISARMED",
    [TX_SP_R_LINK]              = "LINK VERLOREN",
    [TX_SP_R_SUPPLY_OFF]        = "NETZTEIL AUS",
    [TX_SP_R_SUPPLY_LOST]       = "NETZTEIL ANTWORTET NICHT",
    [TX_SP_R_STALE]             = "KEINE MESSWERTE",
    [TX_SP_R_RATE]              = "MESSRATE",
    [TX_SP_R_NOT_ARMED]         = "NICHT ARMED",
    [TX_SP_R_NO_POWER]          = "AUSGANG NICHT GEMELDET",
    [TX_SP_R_SUPPLY_ON]         = "NETZTEIL BLEIBT EIN",
    [TX_SP_R_TOUCH]             = "TOUCH VERLOREN",
    [TX_SP_R_NO_BEEPS]          = "KEINE PIEPTÖNE",
    [TX_SP_R_HIGH]              = "STROM BLEIBT HOCH",
    [TX_SP_R_TIMEOUT]           = "ZEITLIMIT",
    [TX_SP_R_HAND]              = "NICHT BESTÄTIGT",
    [TX_SP_R_USER]              = "ABGEBROCHEN",
    [TX_SP_R_LEFT]              = "SEITE VERLASSEN",
    [TX_SP_RUN]                 = "LAUF",
    [TX_SP_BEEPS_GROUP]         = "PIEPTÖNE IN DIESER GRUPPE",
    [TX_SP_SELECTION]           = "AUSWAHL %u VON %u   %s",
    [TX_SP_DO_ARMING]           = "ARM des Prüfstands, Throttle auf MIN, Netzteil aus.",
    [TX_SP_DO_SIGNAL]           = "Throttle auf %s für den Einstieg; Netzteil ein in %u ms.",
    [TX_SP_DO_POWER]            = "Netzteil schaltet ein mit %u.%02u V.",
    [TX_SP_DO_ENTRY]            = "Eingeschaltet bei %s; Menü erwartet in %u.%u s.",
    [TX_SP_DO_HOLD]             = "Weiter halten: noch %u.%u s.",
    [TX_SP_DO_LET_GO]           = "Jetzt loslassen; Menü erwartet in %u.%u s.",
    [TX_SP_DO_ITEMS]            = "Zähle Punktgruppen; Punkt %u wird mit Stick auf %s gewählt.",
    [TX_SP_DO_VALUES]           = "Zähle Wertgruppen; Wert %u wird mit Stick auf %s gespeichert.",
    [TX_SP_DO_STORE_MOVE]       = "Stick auf %s speichert die Auswahl; gehalten %u ms.",
    [TX_SP_DO_STORE_HOLD]       = "%u ms an der Auswahl gehalten, während der ESC antwortet.",
    [TX_SP_DO_CYCLE]            = "Netzteil %u ms aus vor dem nächsten Einschalten.",
    [TX_SP_DO_OFF]              = "Netzteil schaltet aus; Stick bleibt bis dahin auf %s.",
    [TX_SP_LAST_NONE]           = "LETZTE GRUPPE  noch keine",
    [TX_SP_LAST]                = "LETZTE GRUPPE  %u  %s",
    [TX_SP_NOT_CLEAN]           = "KEINE SAUBERE GRUPPE",
    [TX_SP_TWO_IN_ROW]          = "IN FOLGE, ZWEI HINTEREINANDER",
    [TX_SP_IN_ORDER]            = "IN FOLGE",
    [TX_SP_NOT_IN_ORDER]        = "NICHT IN FOLGE",
    [TX_SP_STATS]               = "GRUPPEN %u   EINSCHALTUNGEN %u   THROTTLE %s   NETZTEIL %s",
    [TX_SP_CURRENT]             = "STROM %d mA   GRUND %d mA   MESSWERTE ALLE %u ms",
    [TX_SP_TONE_HEAD]           = "ABGRIFF %s   TONHÖHE %s   VERLOREN %u   VERPASST %u",
    [TX_SP_TONE_RUNNING]        = "LÄUFT",
    [TX_SP_TONE_OVERRUN]        = "ÜBERLAUF",
    [TX_SP_TONE_WAITING]        = "WARTET",
    [TX_SP_TONE_NO_PAGE]        = "KEINE TONE-PAGE",
    [TX_SP_TONE_REFUSED]        = "PIN BELEGT",
    [TX_SP_TONE_STOPPED]        = "LÄUFT NICHT",
    [TX_SP_TONE_BEEPS]          = "PIEPTÖNE",
    [TX_SP_TONE_NONE]           = "noch keine",
    [TX_SP_TONE_BEEP]           = "#%u  %u.%u ms  %u.%u Hz",
    [TX_SP_ENDS_RUN]            ="STOP oder ABBRECHEN beendet den Lauf: Throttle auf MIN, Netzteil aus, DISARMED.",
    [TX_SP_ABORT]               = "ABBRECHEN",
    [TX_SP_RESULT]              = "ERGEBNIS",
    [TX_SP_ABORTED_WHY]         = "ABGEBROCHEN: %s",
    [TX_SP_MADE_N]              = "%u von %u Auswahlen ausgeführt.",
    [TX_SP_MADE]                = "AUSGEFÜHRT",
    [TX_SP_NOT_MADE]            = "NICHT AUSGEFÜHRT",
    [TX_SP_MADE_CUT]            = "UNSICHER",
    [TX_SP_MORE]                = "UND %u WEITERE, %u DAVON AUSGEFÜHRT",
    [TX_SP_MORE_UNSURE]         = "UND %u WEITERE, %u DAVON AUSGEFÜHRT, %u UNSICHER",
    [TX_SP_TONES_1]             = "Die eigenen Töne des ESC nach einer Auswahl werden nicht geprüft:",
    [TX_SP_TONES_2]             = "darauf hören, oder den ESC mit seiner Programmierkarte auslesen.",
    [TX_SP_SAFE_NOW]            = "Throttle auf MIN, Netzteil aus, Prüfstand DISARMED.",
    [TX_SP_FROM_PROFILE]        = "AUS PROFIL",
    [TX_SP_TIMING_TITLE]        = "TIMING UND ERKENNUNG",
    [TX_SP_TIMING_NOTE]         = "Kein ESC wurde aufgezeichnet: jeder Wert ist ein Vorgabewert, keine Messung.",
    [TX_SP_DEFAULTS]            = "VORGABEN",
    [TX_SP_CHANGE]              = "ÄNDERN",
    [TX_SP_ACTION]              = "AKTION, NICHT SETZBAR",
    [TX_SP_NOTHING_TO_CHOOSE]   = "NICHTS ZU WÄHLEN",
    [TX_SP_KEEP]                = "BEHALTEN",
    [TX_SP_ONLY_WHEN]           = "%u %s, nur wenn %s",
    [TX_SP_ONLY_ON]             = "%u %s, nur bei %u der Modelle",
    [TX_SP_DEFAULT_MARK]        = "(Vorgabe)",
    [TX_SP_PICK_VALUE]          = "Wert zum Ändern wählen; BEHALTEN lässt ihn.",
    [TX_SP_UNVERIFIED]          = "Das Profil ist ungeprüft.",
    [TX_SP_RUN_N]               = "START %u",
    [TX_SP_RUN_BTN]             = "START",
    [TX_SP_TWO_STAGE_MENU]      = "MENÜ ZWEISTUFIG",
    [TX_SP_ONE_STAGE_MENU]      = "MENÜ EINSTUFIG",
    [TX_SP_SHORT_LONG]          = "KURZE/LANGE PIEPTÖNE",
    [TX_SP_COUNTED]             = "GEZÄHLTE PIEPTÖNE",
    [TX_SP_ONE_CHANGE]          = "EINE ÄNDERUNG JE EINSCHALTEN",
    [TX_SP_MANY_CHANGES]        = "MEHRERE ÄNDERUNGEN JE EINSCHALTEN",
    [TX_SP_SUPPLY_ENTRY]        = "NETZTEIL %u.%02u V  %u.%02u A   EINSTIEG %u.%u s%s",
    [TX_SP_FROM_PROFILE_MARK]   = "(Profil)",
    [TX_SP_FROM_SETTING_MARK]   = "(Einstellung)",
    [TX_SP_WARN_TITLE]          = "KEIN PROPELLER, MOTOR GESICHERT?",
    [TX_SP_WARN_1]              = "Der Lauf versorgt diesen ESC aus dem Netzteil und fährt Throttle auf MAX und",
    [TX_SP_WARN_2]              = "zurück, um durch das Programmiermenü zu schalten. In seltenen Fällen kann ein",
    [TX_SP_WARN_3]              = "Motor anlaufen und drehen. Ein angeschlossener Motor muss fest montiert sein",
    [TX_SP_WARN_4]              = "und darf keinen Propeller tragen. Ein Lastwiderstand anstelle des Motors geht",
    [TX_SP_WARN_5]              = "ebenso. Die Pieptöne werden aus dem Strom gezählt.",
    [TX_SP_WARN_SUPPLY]         = "NETZTEIL %u.%02u V  %u.%02u A   %u ÄNDERUNG",
    [TX_SP_WARN_SUPPLY_N]       = "NETZTEIL %u.%02u V  %u.%02u A   %u ÄNDERUNGEN",
    [TX_SP_WARN_UNVERIFIED]     = "Das Profil ist ungeprüft, und jede Pieptonzeit ist ein Vorgabewert.",
    [TX_SP_HOLD_TO_RUN]         = "HALTEN ZUM STARTEN",
    [TX_SP_WARN_HAND]           = "VOR HALTEN ZUM STARTEN, AM ESC:",
    [TX_SP_WARN_HAND_WAIT]      = "Netzteil meldet nicht aus: ausschalten. Handgriffe am ESC erst, wenn es aus meldet.",
    [TX_SP_WARN_HAND_LATER]     = "Spätere Handgriffe: der Lauf hält für jeden an und wartet auf ERLEDIGT.",
    [TX_SP_WARN_HAND_READ]      = "%u Handgriffe: jeden unter ALLE HANDGRIFFE lesen; dann zählt HALTEN ZUM STARTEN.",
    [TX_SP_STEPS_BTN]           = "ALLE HANDGRIFFE",
    [TX_SP_HAND_BTN]            = "MANUELLER EINGRIFF NÖTIG",
    [TX_SP_HAND_TAG]            = "HAND",
    [TX_SP_HAND_WHEN_BEFORE_POWER] = "VOR DEM EINSCHALTEN",
    [TX_SP_HAND_WHEN_AT_POWER]  = "WÄHREND DES EINSCHALTENS",
    [TX_SP_HAND_WHEN_AT_POWER_MS] = "WÄHREND DES EINSCHALTENS, %u.%u s GEHALTEN",
    [TX_SP_HAND_WHEN_BEFORE_MENU] = "NACH DEM EINSTIEG, VOR DEM MENÜ",
    [TX_SP_HAND_WHEN_DURING_MENU] = "WÄHREND DAS MENÜ TÖNT",
    [TX_SP_HAND_WHEN_BEFORE_OFF] = "BEVOR DAS NETZTEIL AUSSCHALTET",
    [TX_SP_HAND_WHEN_AFTER]     = "NACH DEM PROGRAMMIEREN",
    [TX_SP_HAND_ASKS]           = "Der Lauf fordert jeden Handgriff rechtzeitig an und wartet auf ERLEDIGT.",
    [TX_SP_HAND_NOT_RUN]        = "Der Prüfstand fährt dieses Profil nicht: %s.",
    [TX_SP_HAND_OVER]           = "Der Lauf ist vorbei: die Handgriffe nach dem Programmieren jetzt ausführen.",
    [TX_SP_HAND_OVER_LIVE]      = "Netzteil meldet nicht aus: den ESC erst berühren, wenn es aus meldet.",
    [TX_SP_HAND_AFTER_N]        = "%u Handgriffe nach dem Programmieren: MANUELLER EINGRIFF NÖTIG oben nennt sie.",
    [TX_SP_HAND_UNDO]           = "ESC prüfen: was vor dem Einschalten gesteckt wurde, kann noch stecken.",
    [TX_SP_HAND_LOCK]           = "Netzteil aus, bevor der ESC bestätigt hat: er kann gesperrt sein. Prüfen.",
    [TX_SP_HAND_CUT]            = "Netzteil aus, bevor der ESC bestätigt hat: der Modus ist evtl. nicht gespeichert.",
    [TX_SP_PROMPT_TITLE]        = "JETZT VON HAND",
    [TX_SP_PROMPT_OFF]          = "Netzteil aus, Throttle auf %s. Jetzt ausführen, dann ERLEDIGT tippen.",
    [TX_SP_PROMPT_AT_POWER]     = "Jetzt beginnen und dabei bleiben: ERLEDIGT schaltet das Netzteil ein.",
    [TX_SP_PROMPT_HOLD]         = "Nach dem Einschalten %u.%u s weiter halten.",
    [TX_SP_PROMPT_ON]           = "Der ESC ist versorgt, Throttle auf %s. Jetzt ausführen, dann ERLEDIGT tippen.",
    [TX_SP_PROMPT_END]          = "Der ESC ist versorgt, Throttle auf %s. Nicht berühren: beobachten, dann ERLEDIGT.",
    [TX_SP_PROMPT_LISTEN]       = "Der ESC ist versorgt, Throttle auf %s. Jetzt ausführen; der Lauf hört zu.",
    [TX_SP_PROMPT_HEARD]        = "Hört der Lauf das Menü in Folge, geht er selbst weiter; ERLEDIGT sofort.",
    [TX_SP_PROMPT_LEFT]         = "Ohne ERLEDIGT in %u s endet der Lauf: Throttle auf MIN, Netzteil aus, DISARMED.",
    [TX_SP_PROMPT_LEFT_END]     = "Ohne ERLEDIGT in %u s endet der Lauf: Netzteil aus, der ESC kann sich sperren.",
    [TX_SP_PROMPT_LEFT_CUT]     = "Ohne ERLEDIGT in %u s endet der Lauf: Netzteil aus, Modus evtl. nicht gespeichert.",
    [TX_SP_HAND_DONE]           = "ERLEDIGT",
    [TX_SP_POWER_UP_AT]         = "EINSCHALTEN BEI %s",

    /* ------------------- the stick engine's refusals, by their English */
    [TX_ESC_WHY_NO_PROFILE]     = "kein Profil",
    [TX_ESC_WHY_PERSON]         = "braucht eine Person am ESC",
    [TX_ESC_WHY_NO_PROCEDURE]   = "kein nutzbares Verfahren",
    [TX_ESC_WHY_AFTER_POWER]    = "Einstieg nach Einschalten",
    [TX_ESC_WHY_MELODY]         = "Melodie-Menü",
    [TX_ESC_WHY_YES_NO]         = "Ja/Nein-Menü",
    [TX_ESC_WHY_POSITION]       = "Stickpositions-Menü",
    [TX_ESC_WHY_OWN_KIND]       = "Menü eigener Art",
    [TX_ESC_WHY_PITCH]          = "Töne nach Tonhöhe getrennt",
    [TX_ESC_WHY_NO_ITEMS]       = "keine Punkte",
    [TX_ESC_WHY_NO_SELECT]      = "keine Auswahlbewegung",
    [TX_ESC_WHY_REST_ENTRY]     = "Ruhe ohne Einstiegszeit",
    [TX_ESC_WHY_STORE_TWO]      = "Speichern, zweistufig",
    [TX_ESC_WHY_TWO_MOVES]      = "2 Bewegungen, ohne Werttöne",
    [TX_ESC_WHY_SELECT_REST]    = "Auswahl = Ruhestellung",
    [TX_ESC_WHY_VALUE_SELECT]   = "Wertbewegung = Auswahl",
    [TX_ESC_WHY_ONE_MOVE]       = "Punkt und Wert: 1 Bewegung",
    [TX_ESC_WHY_MANY_ONE]       = "viele Änderungen, einstufig",
    [TX_ESC_WHY_COUNTED_ONE]    = "Punkte gezählt, einstufig",
    [TX_ESC_WHY_REPEAT]         = "Werte wiederholen sich",
    [TX_ESC_WHY_STORE_SELECT]   = "Speichern = Auswahl",
    [TX_ESC_WHY_NO_TIMING]      = "kein Timing",
    [TX_ESC_WHY_NOTHING]        = "nichts zu ändern",
    [TX_ESC_WHY_TOO_MANY]       = "zu viele Änderungen",
    [TX_ESC_WHY_NO_ITEM]        = "kein solcher Punkt",
    [TX_ESC_WHY_ACTIONS]        = "Reset und Exit sind Aktionen, keine Werte",
    [TX_ESC_WHY_NO_VALUE]       = "kein solcher Wert",
    [TX_ESC_WHY_ZERO]           = "Wert 0 wird nicht gepiept",
    [TX_ESC_WHY_ONE_PER_ITEM]   = "eine Änderung je Punkt",
    [TX_ESC_WHY_BEEP_GAP]       = "PIEPTON MIN und PAUSE MIN über 0",
    [TX_ESC_WHY_LONG]           = "LANG über PIEPTON MIN",
    [TX_ESC_WHY_LONG_MAX]       = "LANG MAX über LANG",
    [TX_ESC_WHY_GROUP_GAP]      = "GRUPPENPAUSE über PAUSE MIN",
    [TX_ESC_WHY_THRESHOLD]      = "SCHWELLE über HYSTERESE",
    [TX_ESC_WHY_ENTRY]          = "EINSTIEG über 500 ms",
    [TX_ESC_WHY_SELECT_WINDOW]  = "GRUPPENPAUSE verfehlt das Auswahlfenster",
    [TX_ESC_WHY_VALUE_WINDOW]   = "GRUPPENPAUSE verfehlt das Wertfenster",
    [TX_ESC_WHY_NO_RUN]         = "kein Lauf",
    [TX_ESC_WHY_ONE_VALUE]      = "ein Wert: nichts zu wählen",
    [TX_ESC_WHY_HAND]           = "Handgriff",
    [TX_ESC_WHY_ENTRY_POS]      = "Änderungen brauchen verschiedene Einschaltstellungen",
    [TX_ESC_WHY_ENTRY_TIME]     = "Änderungen brauchen verschiedene Einstiegszeiten",
    [TX_ESC_WHY_MENU_REST]      = "Menüstart, Ruhe anderswo",
    [TX_ESC_WHY_AFTER_NONE]     = "eine Bewegung nach dem Wert bewegt nichts",
    [TX_ESC_WHY_AFTER_TWO]      = "Bewegungen nach dem Wert, zweistufig",

    /* ----------------------------------------------------------- SERVO */
    [TX_SV_PG_OUTPUT]           = "AUSGANG",
    [TX_SV_PG_TEST]             = "TEST",
    [TX_SV_PG_LIMITS]           = "GRENZEN",
    [TX_SV_PG_DUT]              = "PRÜFLING",
    [TX_SV_ROW_TYPE]            = "TYP",
    [TX_SV_ROW_RATE]            = "FRAME RATE",
    [TX_SV_ROW_MIN]             = "PULS MIN",
    [TX_SV_ROW_CENTRE]          = "PULS CENTRE",
    [TX_SV_ROW_MAX]             = "PULS MAX",
    [TX_SV_ROW_TRIM]            = "TRIM",
    [TX_SV_ROW_TRAVEL]          = "WEG",
    [TX_SV_ROW_REVERSE]         = "REVERSE",
    [TX_SV_ROW_CURVE]           = "KURVE",
    [TX_SV_ROW_SPEED]           = "TEMPO",
    [TX_SV_ROW_RANGE]           = "BEREICH",
    [TX_SV_ROW_LEN_BY]          = "LÄNGE NACH",
    [TX_SV_ROW_LEN_S]           = "TESTZEIT",
    [TX_SV_ROW_MOVES]           = "BEWEGUNGEN",
    [TX_SV_ROW_DWELL]           = "VERWEILEN",
    [TX_SV_ROW_SETTLE]          = "EINSCHWINGEN",
    [TX_SV_ROW_STEP_48]         = "STUFE 4.8 V",
    [TX_SV_ROW_STEP_60]         = "STUFE 6.0 V",
    [TX_SV_ROW_HV]              = "HV SERVO",
    [TX_SV_ROW_STEP_74]         = "STUFE 7.4 V",
    [TX_SV_ROW_STEP_84]         = "STUFE 8.4 V",
    [TX_SV_ROW_BROWNOUT]        = "BROWN-OUT",
    [TX_SV_ROW_V_MAX]           = "SPANNUNG MAX",
    [TX_SV_ROW_I_MAX]           = "STROM MAX",
    [TX_SV_ROW_STALL]           = "BLOCKIERT AB",
    [TX_SV_ROW_IDLE]            = "RUHESTROM",
    [TX_SV_ROW_HOLD]            = "HALTESTROM",
    [TX_SV_ROW_TRAVEL_TIME]     = "STELLZEIT",
    [TX_SV_ROW_NAME]            = "NAME",
    [TX_SV_ROW_REPORT]          = "BERICHT",
    [TX_SV_ROW_ENC]             = "AS5600",
    [TX_SV_ROW_ENC_CENTRE]      = "ENC-MITTE",
    [TX_SV_SERVO_TYPE]          = "SERVOTYP",
    [TX_SV_CUSTOM]              = "EIGENE",
    [TX_SV_DUT_TITLE]           = "PRÜFLING",
    [TX_SV_NOT_RECORDED]        = "OHNE DATEI",
    [TX_SV_WRITING]             = "SCHREIBT",
    [TX_SV_AUTO_TEST]           = "AUTOMATISCHER TEST",
    [TX_SV_STEP_OF]             = "%s %u VON %u  %.2f V",
    [TX_SV_PHASE_OF]            = "%s %u VON %u",
    [TX_SV_TEST_VERDICT]        = "TEST %s",
    [TX_SV_TRAVEL_HOLD]         = "STELLZEIT %lu ms  HALTEN %.2f A",
    [TX_SV_STOP_TEST]           = "TEST BEENDEN",
    [TX_SV_START_TEST]          = "TEST STARTEN",
    [TX_SV_COMMANDED]           = "PULSBREITE",
    [TX_SV_MEASURED]            = "GEMESSEN",
    [TX_SV_CURRENT]             = "STROM",
    [TX_SV_SUPPLY]              = "NETZTEIL",
    [TX_SV_SOURCE_INA]          = "INA3221 CH1",
    [TX_SV_METER_MODEL]         = "MODELL",
    [TX_SV_SET]                 = "SOLL",
    [TX_SV_SPEED]               = "TEMPO",
    [TX_SV_SPEED_LIMITS]        = "TEMPO BEGRENZT DEN SWEEP",
    [TX_SV_RANGE]               = "BEREICH",
    [TX_SV_CENTRE_BTN]          = "ZENTRIEREN",
    [TX_SV_PAUSE]               = "PAUSE",
    [TX_SV_PAUSED]              = "PAUSIERT",
    [TX_SV_RELEASE]             = "FREIGEBEN",
    [TX_SV_IN_FORCE_1]          = "Aktiv: jedes PWM-Ruder läuft mit %u Hz.",
    [TX_SV_IN_FORCE_2]          = "Ein PPM-Ausgang behält seinen eigenen Frame.",
    [TX_SV_REFUSED_1]           = "ABGELEHNT: ein Ruder teilt einen PWM-Slice mit",
    [TX_SV_REFUSED_2]           = "einem Ausgang anderer Rate. Die Pins behalten ihre.",
    [TX_SV_UNSUPPORTED_1]       = "Dieser Koprozessor nimmt keine Frame Rate: jeder",
    [TX_SV_UNSUPPORTED_2]       = "PWM-Ausgang läuft mit der seiner Bindung, 50 Hz.",
    [TX_SV_UNSENT_1]            = "Die Rate geht mit der nächsten Position",
    [TX_SV_UNSENT_2]            = "an den Koprozessor.",
    [TX_SV_RUNNING]             = "LÄUFT: STUFE %u VON %u",
    /* The verdict and not the file: "ZULETZT NICHT BESTANDEN BENCH012.CSV"
     * is 36 cells in a 29-cell line, and the left card names the file.
     * %.0s takes the file's argument and prints none of it. */
    [TX_SV_LAST]                = "ZULETZT %s%.0s",
    [TX_SV_TAP_HV]              = "TIPPEN: HV-WARNUNG",
    [TX_SV_HOLD_START]          = "2 S HALTEN ZUM STARTEN",
    [TX_SV_FASTEST]             = "Höchste Rate mit diesen Pulsen: %u Hz (%s Pause).",
    [TX_SV_AT_START]            = "Typ und Rate starten als STANDARD PWM 50 Hz.",
    [TX_SV_LIMITS_1]            = "SPANNUNG MAX und STROM MAX sind die Obergrenzen",
    [TX_SV_LIMITS_2]            = "der Seite SUPPLY.  Eine Grenze von 0 wird",
    [TX_SV_LIMITS_3]            = "nicht geprüft.  Über BLOCKIERT AB gilt das",
    [TX_SV_LIMITS_4]            = "Servo als blockiert.",
    [TX_SV_DUT_NOTE]            = "Der Name steht über jedem Testbericht.",
    [TX_SV_ENC_NOTE_1]          = "AS5600: Winkelsensor an der Hornwelle.",
    [TX_SV_ENC_NOTE_2]          = "ENC-MITTE tippen, wenn der Servo in Neutral steht.",
    [TX_SV_HOLD_TO_APPLY]       = "HALTEN ZUM ÜBERNEHMEN",
    [TX_SV_DESTROY]             = "KANN DAS SERVO ZERSTÖREN",
    [TX_SV_DESTROY_WHAT]        = "%s bei %u Hz, %u-%u us",
    [TX_SV_DESTROY_1]           = "Nur für ein dafür gebautes Servo: Datenblatt prüfen.",
    [TX_SV_DESTROY_2]           = "Ein anderes Servo überhitzt oder blockiert binnen",
    [TX_SV_DESTROY_3]           = "Sekunden und wird zerstört.",
    [TX_SV_DESTROY_4]           = "Ein analoges Servo verträgt höchstens 60 Hz.",
    [TX_SV_DESTROY_5]           = "Jeder Neustart kehrt zu STANDARD PWM 50 Hz zurück.",
    [TX_SV_HV_ONLY]             = "NUR HV-SERVOS",
    [TX_SV_HV_ON_AT]            = "AUSGANG EIN BEI %.2f V",
    [TX_SV_HV_STEPS]            = "TESTSTUFEN BIS %.2f V",
    [TX_SV_HV_VOLTAGE]          = "SPANNUNG %.2f -> %.2f V",
    [TX_SV_HV_1]                = "Standardservos sind für 4.8 bis 6.0 V ausgelegt.",
    [TX_SV_HV_2]                = "Über 6.0 V bleibt nur ein als HV (Hochvolt)",
    [TX_SV_HV_3]                = "spezifiziertes Servo innerhalb seiner Nennwerte.",
    [TX_SV_HV_4]                = "Ein Standardservo kann sofort zerstört werden.",
    [TX_SV_HV_5]                = "Vor dem Übernehmen das Datenblatt des Servos prüfen.",
    [TX_SV_HV_LIVE]             = "Der Ausgang ist ein: die Spannung ändert sich sofort.",

    /* ----------- the alert band: the panel's control task raises these */
    [TX_ALERT_TOUCH_LOST_STOP]  = "Touch verloren, während STOP gehalten wurde -- gestoppt",
    [TX_ALERT_TOUCH_LOST_ARMING]= "Touch verloren beim ARM -- gestoppt",
    [TX_ALERT_NO_CARD_RUN]      = "keine Karte -- dieser Lauf wird nicht aufgezeichnet",
    [TX_ALERT_CARD_UNREADABLE]  = "Karte nicht lesbar -- Lauf nicht aufgezeichnet",
    [TX_ALERT_CARD_FULL]        = "Karte voll oder nicht beschreibbar -- Lauf nicht aufgezeichnet",
    [TX_ALERT_CARD_ROWS_SHORT]  = "die Karte nimmt keine Zeilen mehr an -- das Log ist unvollständig",
    [TX_ALERT_CARD_LAST_WRITE]  = "die Karte versagte beim letzten Schreiben -- das Log ist unvollständig",
    [TX_ALERT_CARD_SERVO]       = "keine Karte oder Karte voll -- Servotest nicht aufgezeichnet",
    [TX_ALERT_CARD_SERVO_SHORT] = "die Karte versagte -- die Dateien des Servotests sind unvollständig",
    [TX_ALERT_CARD_ROWS_PAST]   = "die Karte nimmt keine Zeilen mehr an -- Lauf ab hier nicht aufgezeichnet",
    [TX_ALERT_POLES]            = "Koprozessor lehnte die Polzahl ab",
    [TX_ALERT_PULSE_RANGE_UNKNOWN]= "Koprozessor meldete seinen Pulsbereich nicht",
    [TX_ALERT_PULSE_ORDER]      = "Leerlaufpuls muss unter dem Vollpuls liegen -- nicht gesendet",
    [TX_ALERT_PULSE_REFUSED]    = "Koprozessor lehnte den Pulsbereich ab",
    [TX_ALERT_PDMINI_OLD]       = "Koprozessor zu alt, um den PD mini zurückzusetzen",
    [TX_ALERT_PDMINI_WIRING]    = "Verdrahtung des PD mini in SETUP geändert -- Ausgang aus",
    [TX_ALERT_SUPPLY_CHANGED]   = "Netzteil in SETUP geändert -- Ausgang aus",
    [TX_ALERT_SUPPLY_SILENT]    = "Netzteil antwortet nicht -- Ausgang aus",
    [TX_ALERT_SUPPLY_TRIP]      = "Netzteil abgeschaltet über %u.%02u %s -- Ausgang aus",
    [TX_ALERT_TOUCH_ARM_AGAIN]  = "Touch verloren beim ARM -- erneut ARM",
    [TX_ALERT_TOUCH_STOPPED]    = "Touch antwortet nicht mehr -- DISARMED",
    [TX_ALERT_SERVO_NOT_RELEASED]= "Servoausgang nicht freigegeben -- erneut ARM",
    [TX_ALERT_SERVO_RATE]       = "Frame Rate des Servos unbekannt -- erneut ARM",
    [TX_ALERT_ARM_REFUSED]      = "Koprozessor lehnte ARM ab",
    [TX_ALERT_SWEEP_RESUME_OLD] = "Koprozessor älter als 4.6 -- der Sweep beginnt von vorn",
    [TX_ALERT_SWEEP_RESUME_REFUSED] = "Koprozessor lehnte das Fortsetzen ab -- der Sweep beginnt von vorn",
    [TX_ALERT_SWEEP_RESUME_UNTIMED] = "Pause unbeantwortet -- der Sweep beginnt von vorn",
    [TX_ALERT_CARD_SLOW]        = "die Karte kam nicht nach -- Lauf nicht aufgezeichnet",
    [TX_ALERT_CARD_GAPS]        = "die Karte fiel zurück -- das Log hat Lücken",
    [TX_ALERT_TOUCH_SWITCH_ON]  = "Touch verloren beim Einschalten -- Ausgang aus",
    [TX_ALERT_PDMINI_OFF]       = "PD mini schaltete seinen Ausgang ab -- Ausgang aus",
    [TX_ALERT_SUPPLY_OFF_REMOTE]= "Netzteil am Koprozessor abgeschaltet",
    [TX_ALERT_SUPPLY_REFUSED_ON]= "Netzteil lehnte EIN ab -- Ausgang aus",
    [TX_ALERT_PDMINI_PINS]      = "Pins des PD mini abgelehnt -- siehe SETUP ANSCHLÜSSE",
    [TX_ALERT_PDMINI_SWITCH]    = "Ausgang des PD mini schaltet nicht",
    [TX_ALERT_PDMINI_SET]       = "Sollwerte des PD mini werden nicht übernommen",
    [TX_ALERT_PDMINI_SAG]       = "Eingang des PD mini %u.%02u V unter Sollwert %u.%02u V + 0,5 V -- Ausgang aus",
    [TX_ALERT_PDMINI_WIRING_LIVE] = "Verdrahtung des PD mini abgelehnt -- sein Ausgang kann an sein",
    [TX_ALERT_COPRO_DISARMED]   = "Koprozessor DISARMED -- erneut ARM",
    [TX_ALERT_MISMATCH]         = "Protokoll passt nicht -- kein ARM",
    [TX_ALERT_NO_SUPPLY_PAGE]   = "Koprozessor ohne SUPPLY-Page -- PD mini nicht angesteuert",
    [TX_ALERT_TOUCH_NO_ANSWER]  = "Touch antwortete nicht -- der Prüfstand nimmt kein ARM an",
    [TX_ALERT_NO_SENSE_PAGE]    = "Koprozessor ohne SENSE-Page -- Strommonitore nicht gelesen",
    [TX_ALERT_SENSE_PINS_UNSET] = "Sensor-SDA oder -SCL nicht gesetzt -- siehe SETUP ANSCHLÜSSE",
    [TX_ALERT_SENSE_SAME_ADDR]  = "INA228 und INA3221 beide auf 0x%02X -- siehe SETUP ANSCHLÜSSE",
    [TX_ALERT_SENSE_PINS]       = "Sensor-Pins GP%d/GP%d abgelehnt -- siehe SETUP ANSCHLÜSSE",
    [TX_ALERT_SENSE_I228_SETUP] = "INA228 Shunt oder Höchststrom abgelehnt -- siehe SETUP ANSCHLÜSSE",
    [TX_ALERT_SENSE_I3221_SETUP] = "INA3221-Einstellung abgelehnt -- siehe SETUP ANSCHLÜSSE",
    [TX_ALERT_SENSE_SILENT]     = "%s antwortet nicht auf 0x%02X",
    [TX_ALERT_SENSE_SILENT_FOUND] = "%s antwortet nicht auf 0x%02X -- 0x%02X antwortet",
    [TX_ALERT_SENSE_WRONG]      = "0x%02X antwortet mit %04Xh, kein %s -- nicht benutzt",
    [TX_ALERT_SENSE_STUCK]      = "Sensorbus hängt: SDA auf low -- wird freigetaktet",
    [TX_ALERT_SENSE_I228_CLIPPED] = "INA228-Strom am Ende des Messbereichs -- Strom ist eine Grenze",
    [TX_ALERT_SENSE_I3221_CLIPPED] = "INA3221 CH%u übersteuert bei %u.%02u A -- Strom ist eine Grenze",
    [TX_ALERT_ENC_OLD]          = "Koprozessor älter als 4.9 -- AS5600 nicht gelesen",
    [TX_ALERT_SERVO_METER_OLD]  = "Koprozessor älter als 4.11 -- Servostrom vom PD mini gelesen",
    [TX_ALERT_I3221_RESET]      = "INA3221 hat sich zurückgesetzt -- Versorgung prüfen",
    [TX_ALERT_ENC_SILENT]       = "AS5600 antwortet nicht an 0x36",
    [TX_ALERT_ENC_NO_MAGNET]    = "AS5600 sieht keinen Magneten -- Magnet auf der Hornwelle prüfen",
    [TX_ALERT_ENC_WEAK]         = "AS5600: Magnet zu schwach -- näher heranbringen",
    [TX_ALERT_ENC_STRONG]       = "AS5600: Magnet zu stark -- weiter weg",
    [TX_ALERT_STORE_OFF]        = "Speicher des Koprozessors aus -- Einstellungen gelten bis zum Neustart",
    [TX_ALERT_NO_TONE_PAGE]     = "Koprozessor ohne TONE-Page -- Phasenabgriff nicht gelesen",
    [TX_ALERT_TONE_PIN]         = "Phasenabgriff an GP%u, %u bis %u Hz abgelehnt -- siehe SETUP ANSCHLÜSSE",
    [TX_ALERT_TONE_SETUP]       = "Phasenabgriff: Sprung, Pause oder Perioden abgelehnt -- siehe SETUP ANSCHLÜSSE",
    [TX_ALERT_TONE_BUSY]        = "Phasenabgriff: Pin GP%u nicht frei -- Abgriff läuft nicht",
    [TX_ALERT_TONE_OVERRUN]     = "Phasenabgriff: Aufnahme übergelaufen -- Pieptöne abgeschnitten",

    /* ----------------- the splash's details, from the panel's start-up */
    [TX_SPLASH_NO_PANEL]        = "kein Panel",
    [TX_SPLASH_NO_ANSWER]       = "keine Antwort",
    [TX_SPLASH_NO_CARD]         = "keine Karte",
    [TX_SPLASH_NVS_MISSING]     = "NVS nicht verfügbar",
    [TX_SPLASH_NOT_OPENED]      = "nicht geöffnet",
    [TX_SPLASH_REFUSED]         = "abgelehnt",
    [TX_SPLASH_WRONG_REPLY]     = "falsche Antwort",
    [TX_SPLASH_NO_LINK]         = "kein Link",
};

/* ------------------------------------------------------- the settings */

/*
 * SETUP draws a label in the heading face in 18 cells and its help in 36;
 * the SUPPLY, SERVO and ESC STICK categories are drawn on their own screens,
 * whose fields test_text holds them to.
 */
static const char *const k_label[SETTING_COUNT] = {
    [SET_PACK_CELLS]          = "Zellen",
    [SET_PACK_MAH]            = "Kapazität",
    [SET_PACK_MOHM]           = "Innenwiderstand",
    [SET_MOTOR_POLES]         = "Motorpole",
    [SET_MOTOR_KV]            = "Nenn-kV",
    [SET_OUT_MIN_US]          = "Leerlaufpuls",
    [SET_OUT_MAX_US]          = "Vollpuls",
    [SET_OUT_RAMP]            = "Rampengrenze",
    [SET_THEME]               = "Design",
    [SET_BRIGHTNESS]          = "Helligkeit",
    [SET_CONTRAST]            = "Kontrast",
    [SET_BACKLIGHT]           = "Beleuchtung",
    [SET_LANGUAGE]            = "Sprache",
    [SET_UNITS]               = "Einheiten",
    [SET_DIM_AFTER]           = "Dimmen nach",
    [SET_PLOT_PAN]            = "Ein Finger schiebt",
    [SET_KNOB_EN]             = "Drehknopf",
    [SET_KNOB_SCALE]          = "Knopf-Skala",
    [SET_INA228_EN]           = "INA228",
    [SET_INA228_ADDR]         = "INA228 Adresse",
    [SET_INA228_UOHM]         = "INA228 Shunt",
    [SET_INA228_MAX_A]        = "INA228 Höchststrom",
    [SET_INA3221_EN]          = "INA3221",
    [SET_INA3221_ADDR]        = "INA3221 Adresse",
    [SET_INA3221_MOHM]        = "INA3221 Shunt",
    [SET_INA3221_CH]          = "INA3221 Kanäle",
    [SET_SENSE_SDA]           = "Sensor-SDA",
    [SET_SENSE_SCL]           = "Sensor-SCL",
    [SET_ENC_EN]              = "AS5600",
    [SET_ENC_CENTRE]          = "AS5600-Mitte",
    [SET_TONE_EN]             = "Phasenabgriff",
    [SET_TONE_PIN]            = "Abgriff-Pin",
    [SET_TONE_F_MIN]          = "Tiefster Ton",
    [SET_TONE_F_MAX]          = "Höchster Ton",
    [SET_TONE_SPLIT]          = "Tonsprung",
    [SET_TONE_GAP]            = "Abgriff-Pause",
    [SET_TONE_PERIODS]        = "Min. Perioden",
    [SET_VIBE_EN]             = "Vibration",
    [SET_OPTICAL_EN]          = "Optischer Tacho",
    [SET_OPTICAL_PIN]         = "Tacho-Pin",
    [SET_PDMINI_EN]           = "PD mini",
    [SET_PDMINI_TX]           = "PD mini TX",
    [SET_PDMINI_RX]           = "PD mini RX",
    [SET_PDMINI_BAUD]         = "PD mini Baud",
    [SET_SUPPLY_V_MAX]        = "Spannung max",
    [SET_SUPPLY_I_MAX]        = "Strom max",
    [SET_SUPPLY_V_START]      = "Startspannung",
    [SET_SUPPLY_I_START]      = "Startstrom",
    [SET_SUPPLY_TRIP_I]       = "Überstrom",
    [SET_SUPPLY_TRIP_V]       = "Überspannung",
    [SET_SUPPLY_TRIP_MS]      = "Abschaltzeit",
    [SET_SUPPLY_CONFIRM_SLIDE] = "Rückfrage Slider",
    [SET_SUPPLY_CONFIRM_KEYS] = "Rückfrage Tastenfeld",
    [SET_SERVO_CURVE]         = "Kurve",
    [SET_SERVO_TEST_HZ]       = "Tempo",
    [SET_SERVO_TEST_RANGE]    = "Bereich",
    [SET_SERVO_LEN_BY]        = "Länge nach",
    [SET_SERVO_LEN_S]         = "Testzeit",
    [SET_SERVO_LEN_MOVES]     = "Bewegungen",
    [SET_SERVO_DWELL_MS]      = "Verweilen",
    [SET_SERVO_SETTLE_MS]     = "Einschwingen",
    [SET_SERVO_STEP_48]       = "Stufe 4.8 V",
    [SET_SERVO_STEP_60]       = "Stufe 6.0 V",
    [SET_SERVO_STEP_74]       = "Stufe 7.4 V",
    [SET_SERVO_STEP_84]       = "Stufe 8.4 V",
    [SET_SERVO_BROWNOUT]      = "Brown-out",
    [SET_SERVO_IDLE_MAX]      = "Ruhestrom max",
    [SET_SERVO_HOLD_MAX]      = "Haltestrom max",
    [SET_SERVO_TRAVEL_MAX_MS] = "Stellzeit max",
    [SET_SERVO_STALL_A]       = "Blockierschwelle",
    [SET_SERVO_REPORT]        = "Bericht",
    [SET_STICK_V]             = "Spannung",
    [SET_STICK_I]             = "Strombegrenzung",
    [SET_STICK_BEEP_MIN]      = "Piepton min",
    [SET_STICK_GAP_MIN]       = "Pause min",
    [SET_STICK_LONG]          = "Lang",
    [SET_STICK_LONG_MAX]      = "Lang max",
    [SET_STICK_GROUP_GAP]     = "Gruppenpause",
    [SET_STICK_ENTRY]         = "Einstieg",
    [SET_STICK_STORE]         = "Speichern",
    [SET_STICK_OFF]           = "Ausschaltzeit",
    [SET_STICK_SILENCE]       = "Stille",
    [SET_STICK_TIMEOUT]       = "Zeitlimit",
    [SET_STICK_THRESHOLD]     = "Schwelle",
    [SET_STICK_HYST]          = "Hysterese",
};

static const char *const k_help[SETTING_COUNT] = {
    [SET_PACK_CELLS]          = "Zellen in Serie im Akku",
    [SET_PACK_MAH]            = "Für die Schätzung der Restladung",
    [SET_PACK_MOHM]           = "Ganzer Akku, für das Einbruchmodell",
    [SET_MOTOR_POLES]         = "eRPM geteilt durch Pole/2 ergibt RPM",
    [SET_MOTOR_KV]            = "Wenn der ESC keinen meldet; 0 = leer",
    [SET_OUT_MIN_US]          = "Breite bei 0 % Throttle",
    [SET_OUT_MAX_US]          = "Breite bei 100 % Throttle",
    [SET_OUT_RAMP]            = "Anstieg des simulierten Prüfstands",
    [SET_THEME]               = "",
    [SET_BRIGHTNESS]          = "Skaliert die Palette; s. Beleuchtung",
    [SET_CONTRAST]            = "Drückt Farben weg vom Mittelgrau",
    [SET_BACKLIGHT]           = "Auf dieser Platine nur ein/aus",
    [SET_LANGUAGE]            = "",
    [SET_UNITS]               = "",
    [SET_DIM_AFTER]           = "0 hält die volle Helligkeit",
    [SET_PLOT_PAN]            = "Zoom im Log-Plot: Ziehen verschiebt",
    [SET_KNOB_EN]             = "AS5600 dreht den aktiven Regler",
    [SET_KNOB_SCALE]          = "Knopfgrad je ganzem Reglerweg",
    [SET_INA228_EN]           = "I2C-Strommonitor im ESC-Strompfad",
    [SET_INA228_ADDR]         = "Pins A0/A1; MATEK ab Werk: 0x45",
    [SET_INA228_UOHM]         = "Shunt, über dem der INA228 misst",
    [SET_INA228_MAX_A]        = "Höchststrom; wählt den Messbereich",
    [SET_INA3221_EN]          = "Dreikanal-Monitor der Servoschiene",
    [SET_INA3221_ADDR]        = "DAOKAI: 0x40 mit A0-Brücke nach GND",
    [SET_INA3221_MOHM]        = "Je Kanal; 100 misst bis 1.64 A",
    [SET_INA3221_CH]          = "CH1 der Servotest, CH2+3 ein Paar",
    [SET_SENSE_SDA]           = "Koprozessor-GPIO; -1: kein Sensorbus",
    [SET_SENSE_SCL]           = "Folgt Sensor-SDA: der GPIO danach",
    [SET_ENC_EN]              = "Winkelsensor an der Servowelle",
    [SET_ENC_CENTRE]          = "Zähler in Neutral; 4096 je Umdr.",
    [SET_TONE_EN]             = "Pieptöne des ESC an einer Motorphase",
    [SET_TONE_PIN]            = "Koprozessor-GPIO; GP22 ist Pad 29",
    [SET_TONE_F_MIN]          = "Tiefere Töne sind kein Piepton",
    [SET_TONE_F_MAX]          = "Über dem tiefsten Ton; bis 6900 Hz",
    [SET_TONE_SPLIT]          = "Sprung, der Pieptöne trennt; 0 aus",
    [SET_TONE_GAP]            = "Stille, die einen Piepton beendet",
    [SET_TONE_PERIODS]        = "Perioden, die einen Piepton ergeben",
    [SET_VIBE_EN]             = "Beschleunigungssensor zum Wuchten",
    [SET_OPTICAL_EN]          = "Einmal pro Umdrehung, gibt die Phase",
    [SET_OPTICAL_PIN]         = "-1, bis einer verdrahtet ist",
    [SET_PDMINI_EN]           = "Programmierbares Netzteil an UART",
    [SET_PDMINI_TX]           = "Unser TX an DM des Moduls; -1: offen",
    [SET_PDMINI_RX]           = "Unser RX von DP am Modul; -1: offen",
    [SET_PDMINI_BAUD]         = "UART Baudrate des Moduls; AUTO sucht",
    [SET_SUPPLY_V_MAX]        = "Höchste Spannung eines Sollwerts",
    [SET_SUPPLY_I_MAX]        = "Höchste Strombegrenzung als Sollwert",
    [SET_SUPPLY_V_START]      = "Spannungssollwert nach Neustart",
    [SET_SUPPLY_I_START]      = "Strombegrenzung nach Neustart",
    [SET_SUPPLY_TRIP_I]       = "Ausgang aus über diesem Strom; 0 = aus",
    [SET_SUPPLY_TRIP_V]       = "Ausgang aus über dieser Spannung; 0 = aus",
    [SET_SUPPLY_TRIP_MS]      = "Zeit über der Grenze bis zur Abschaltung",
    [SET_SUPPLY_CONFIRM_SLIDE] = "Fragen, bevor der Slider einen Ausgang unter Spannung ändert",
    [SET_SUPPLY_CONFIRM_KEYS] = "Fragen, bevor das Tastenfeld einen Ausgang unter Spannung ändert",
    [SET_SERVO_CURVE]         = "Wie der Test das Servo bewegt",
    [SET_SERVO_TEST_HZ]       = "Kurven pro Sekunde",
    [SET_SERVO_TEST_RANGE]    = "Anteil des Wegs, den der Test fährt",
    [SET_SERVO_LEN_BY]        = "Eine Zeit oder eine Zahl von Bewegungen",
    [SET_SERVO_LEN_S]         = "Dauer jeder Netzteilstufe",
    [SET_SERVO_LEN_MOVES]     = "Bewegungen je Stufe",
    [SET_SERVO_DWELL_MS]      = "Haltezeit an jedem Ende vor dem Weiterfahren",
    [SET_SERVO_SETTLE_MS]     = "Wartezeit nach einer Netzteilstufe vor dem Messen",
    [SET_SERVO_STEP_48]       = "",
    [SET_SERVO_STEP_60]       = "",
    [SET_SERVO_STEP_74]       = "",
    [SET_SERVO_STEP_84]       = "",
    [SET_SERVO_BROWNOUT]      = "Ab 5.0 V abwärts, bis das Servo stehen bleibt",
    [SET_SERVO_IDLE_MAX]      = "Darüber in Ruhe nicht bestanden; 0 = nicht geprüft",
    [SET_SERVO_HOLD_MAX]      = "Darüber beim Halten nicht bestanden; 0 = nicht geprüft",
    [SET_SERVO_TRAVEL_MAX_MS] = "Darüber von Ende zu Ende nicht bestanden; 0 = nicht geprüft",
    [SET_SERVO_STALL_A]       = "Darüber gilt das Servo als blockiert",
    [SET_SERVO_REPORT]        = "Ein Textbericht neben dem Log jedes Tests",
    [SET_STICK_V]             = "0 nimmt sie aus der Zellenzahl des Profils",
    [SET_STICK_I]             = "Grenze des Netzteils für den Lauf",
    [SET_STICK_BEEP_MIN]      = "Kürzester Piepton des ESC",
    [SET_STICK_GAP_MIN]       = "Kürzeste Stille zwischen zwei Pieptönen",
    [SET_STICK_LONG]          = "Ein Piepton ab dieser Länge ist lang",
    [SET_STICK_LONG_MAX]      = "Ein längerer Puls ist kein Piepton",
    [SET_STICK_GROUP_GAP]     = "Stille, die eine Gruppe Pieptöne beendet",
    [SET_STICK_ENTRY]         = "Einschalten bis Menü, wo das Profil keine Zeit nennt",
    [SET_STICK_STORE]         = "Haltezeit an der letzten Auswahl vor dem Ausschalten",
    [SET_STICK_OFF]           = "Netzteil aus zwischen zwei Einstiegen",
    [SET_STICK_SILENCE]       = "So lange kein Piepton beendet den Lauf",
    [SET_STICK_TIMEOUT]       = "Gesuchte Pieptöne in dieser Zeit nicht gehört",
    [SET_STICK_THRESHOLD]     = "Über dem Ruhestrom: ein Piepton",
    [SET_STICK_HYST]          = "Unter der Schwelle minus diesem Wert: Stille",
};

static const char *const k_theme[]  = { "DUNKEL", "HELL" };
static const char *const k_units[]  = { "METRISCH", "IMPERIAL" };
static const char *const k_curve[]  = { "RECHTECK", "SINUS", "DREIECK" };
static const char *const k_len_by[] = { "ZEIT", "BEWEGUNGEN" };

/* The language names each its own; the INA228's and the INA3221's
 * addresses, the INA3221's channels and the baud rates are the same words
 * in every language and are not here. */
static const char *const *const k_options[SETTING_COUNT] = {
    [SET_THEME]               = k_theme,
    [SET_UNITS]               = k_units,
    [SET_SERVO_CURVE]         = k_curve,
    [SET_SERVO_LEN_BY]        = k_len_by,
};

static const char *const k_category[SET_CAT_COUNT] = {
    [SET_CAT_ESC]             = "ESC / PRÜFSTAND",
    [SET_CAT_APP]             = "ANWENDUNG",
    [SET_CAT_IFACE]           = "ANSCHLÜSSE",
    [SET_CAT_SUPPLY]          = "NETZTEIL",
    [SET_CAT_SERVO]           = "SERVOTEST",
    [SET_CAT_STICK]           = "ESC STICK",
};

/* ------------------------------------------------- the servo test's */

/*
 * The SERVO screen's words for a run, and the TXT report.  The CSV a run
 * writes stays English (servo_str()), so a tool reads every run alike.
 * The report's labels pad to column 18 here, one more than the English,
 * because "Strombegrenzung:" is 16 characters.
 */
static const char *const k_servo[SERVO_STR_COUNT] = {
    [SERVO_STR_PHASE_SET]        = "SETZEN",
    [SERVO_STR_PHASE_SETTLE]     = "EINSCHWINGEN",
    [SERVO_STR_PHASE_IDLE]       = "RUHE",
    [SERVO_STR_PHASE_MOVE]       = "BEWEGEN",
    [SERVO_STR_PHASE_HOLD]       = "HOLD",
    [SERVO_STR_PASS]             = "BESTANDEN",
    [SERVO_STR_FAIL]             = "NICHT BESTANDEN",
    [SERVO_STR_ABORTED]          = "ABGEBROCHEN",
    [SERVO_STR_NOT_MEASURABLE]   = "NICHT MESSBAR",
    [SERVO_STR_TEST_STEP]        = "STUFE",
    [SERVO_STR_TEST_BROWNOUT]    = "BROWN-OUT",
    [SERVO_STR_AB_STOP]          = "STOP",
    [SERVO_STR_AB_DISARMED]      = "Prüfstand DISARMED",
    [SERVO_STR_AB_LINK]          = "Link verloren",
    [SERVO_STR_AB_LEFT]          = "Seite SERVO verlassen",
    [SERVO_STR_AB_OPERATOR]      = "vom Bediener gestoppt",
    [SERVO_STR_AB_SETTINGS]      = "Servo-Optionen geändert",
    [SERVO_STR_AB_TOUCH]         = "Touch-Ereignisse verloren",
    [SERVO_STR_AB_SUPPLY_LOST]   = "Netzteil antwortet nicht",
    [SERVO_STR_AB_TRIPPED]       = "Netzteil abgeschaltet",
    [SERVO_STR_AB_SUPPLY_OFF]    = "Netzteilausgang ging aus",
    [SERVO_STR_AB_STALE]         = "seit 1.5 s kein Messwert",
    [SERVO_STR_AB_NOT_ON]        = "Netzteilausgang ging nicht an",
    [SERVO_STR_AB_SET_NOT_TAKEN] = "Sollwert 3 s nicht bestätigt",
    [SERVO_STR_AB_CAP]           = "Stufe über Spannungsobergrenze",
    [SERVO_STR_AB_STALL]         = "1 s über BLOCKIERT AB",
    [SERVO_STR_AB_CC]            = "1 s im Konstantstrom",
    [SERVO_STR_AB_WIN_STALE]     = "0.5 s kein INA3221-Fenster",
    [SERVO_STR_AB_INA_RESET]     = "INA3221 setzte sich zurück",
    [SERVO_STR_AB_INA_SILENT]    = "INA3221 antwortet nicht",
    [SERVO_STR_AB_INA_NO_WINDOW] = "INA3221-Fenster ohne Strom",
    [SERVO_STR_AB_INA_SETUP]     = "INA3221-Einstellung fehlt",
    [SERVO_STR_AB_INA_METER]     = "INA3221 misst nicht mehr",
    [SERVO_STR_START_NO_STEPS]   = "KEINE STUFE GEWÄHLT",
    [SERVO_STR_START_ABOVE_CAP]  = "STUFE ÜBER DEN OBERGRENZEN",
    [SERVO_STR_START_NO_SUPPLY]  = "NETZTEIL ANTWORTET NICHT",
    [SERVO_STR_START_BAD_ENDS]   = "BEREICH ZU KLEIN",
    [SERVO_STR_START_NOT_ARMED]  = "ZUERST ARM",
    [SERVO_STR_START_BUSY]       = "LETZTER BERICHT SCHREIBT NOCH",

    [SERVO_STR_R_TITLE]          = "RCBENCH SERVOTEST-BERICHT",
    [SERVO_STR_R_RESULT]         = "Ergebnis:        %s",
    [SERVO_STR_R_RESULT_WHY]     = "Ergebnis:        %s - %s",
    [SERVO_STR_R_RESULT_UNSEEN]  = "Ergebnis:        %s - bei %u von %u "
                                   "gezählten Bewegungen keine Bewegung im "
                                   "Strom erkannt",
    [SERVO_STR_R_RESULT_BO_UNSEEN] = "Ergebnis:        %s - keine Bewegung "
                                     "erkannt bei %.2f V, der ersten "
                                     "Spannung des Brown-out",
    [SERVO_STR_R_DEVICE]         = "Prüfling:        %s",
    [SERVO_STR_R_FIRMWARE]       = "Firmware:        rcbench %s",
    [SERVO_STR_R_LOG]            = "Log:             die .CSV mit der Nummer "
                                   "dieser Datei, eine Zeile je Messwert des "
                                   "Netzteils",
    [SERVO_STR_R_SUPPLY]         = "Netzteil:        %s",
    [SERVO_STR_R_SUPPLY_MODEL]   = "vom Panel simuliert: jeder Messwert ist berechnet",
    [SERVO_STR_R_READINGS]       = "Messwerte:       %.1f /s vom Netzteil "
                                   "genommen, %.1f /s erreichten den Test",
    [SERVO_STR_R_READINGS_FEW]   = "Messwerte:       weniger als zwei",
    [SERVO_STR_R_SKIPPED]        = "Übersprungen:    %lu Messwerte des "
                                   "Netzteils erreichten den Test nie",
    [SERVO_STR_R_RESOLUTION]     = "Auflösung:       ein Messwert alle %lu "
                                   "ms: eine Stellzeit ist um bis zu so viel "
                                   "zu lang",
    [SERVO_STR_R_RESOLUTION_UNKNOWN] = "Auflösung:       unbekannt",
    [SERVO_STR_R_LAG]            = "Verzögerung:     etwa %u ms von einer "
                                   "Stromänderung bis zum Messwert, der sie "
                                   "zeigt",
    [SERVO_STR_R_REPEATS]        = "Wiederholung:    ein Messwert kann den "
                                   "letzten Wert mehrere Messwerte lang "
                                   "wiederholen",
    [SERVO_STR_R_UPPER_BOUND]    = "Stellzeiten:     eine Obergrenze, nicht "
                                   "gegen die Grenze geprüft",
    [SERVO_STR_R_DURATION]       = "Dauer:           %lu.%01lu s",
    [SERVO_STR_R_ROWS]           = "Logzeilen:       %lu geschrieben, %lu an "
                                   "eine volle Warteschlange verloren",
    [SERVO_STR_R_SETTINGS]       = "AKTIVE EINSTELLUNGEN",
    [SERVO_STR_R_TYPE]           = "Typ:             %s, Centre %u us, %u-%u "
                                   "us, Trim %+d us, Reverse %s",
    [SERVO_STR_R_RATE]           = "Frame Rate:      %u Hz",
    [SERVO_STR_R_DANGER]         = "Kann zerstören:  %s",
    [SERVO_STR_R_DANGER_NONE]    = "keine aktiv",
    [SERVO_STR_R_HV]             = "HV Servo:        %s",
    [SERVO_STR_R_HV_OFF]         = "AUS, keine Stufe über 6.0 V",
    [SERVO_STR_R_HV_ON_RUN]      = "EIN, Stufen über 6.0 V laufen",
    [SERVO_STR_R_HV_ON_NONE]     = "EIN, keine Stufe über 6.0 V gewählt",
    [SERVO_STR_R_ENDS]           = "Enden:           %u us und %u us "
                                   "(BEREICH %u %% von WEG +/-%u deg)",
    [SERVO_STR_R_STEPS]          = "Stufen:         ",
    [SERVO_STR_R_STEPS_NONE]     = " keine",
    [SERVO_STR_R_BROWNOUT]       = "Brown-out:       ab %.2f V abwärts in "
                                   "Schritten von %.2f V bis %.2f V",
    [SERVO_STR_R_BROWNOUT_NOT_RUN] = "Brown-out:       nicht gelaufen",
    [SERVO_STR_R_I_LIMIT]        = "Strombegrenzung: %.2f A",
    [SERVO_STR_R_TIMING]         = "Zeiten:          Einschwingen %u ms, "
                                   "Ruhe %u ms, Verweilen %u ms (Halten "
                                   "gemessen %u ms)",
    [SERVO_STR_R_LEN_MOVES]      = "Länge:           %u Bewegungen je Stufe",
    [SERVO_STR_R_LEN_TIME]       = "Länge:           %u s je Stufe",
    [SERVO_STR_R_LIMITS]         = "Grenzen:         Ruhe %s, Halten %s, "
                                   "Stellzeit %s, Blockieren %.2f A",
    [SERVO_STR_R_ON]             = "EIN",
    [SERVO_STR_R_OFF]            = "AUS",
    [SERVO_STR_R_PER_STEP]       = "ERGEBNISSE JE STUFE (Ströme in A, "
                                   "Zeiten in ms)",
    /* Over the columns of the step lines: 0, 7, 15, 22, 29, 36, 43, 50, 58,
     * 66, 73, 81, 87 and 92, as the English. */
    [SERVO_STR_R_COLUMNS]        = "Soll V Ist V   V min  Ruhe   Schw.  Beweg. Spitze Halt mn Halt mx Stell. Längste Anz.  Spät Unerk.",
    [SERVO_STR_R_STEP_NOT_RUN]   = "%5.2f  nicht gelaufen",
    [SERVO_STR_R_CUT_SHORT]      = " (verkürzt)",
    [SERVO_STR_R_NO_STEP]        = "Keine Stufe lief.",
    [SERVO_STR_R_LATE]           = "Spät: erkannte Bewegungen, die nicht "
                                   "binnen %u ms ankamen.",
    [SERVO_STR_R_UNSEEN]         = "Unerk.: Bewegungen ohne erkannte "
                                   "Bewegung; nicht gemessen, nicht als spät "
                                   "gezählt.",
    [SERVO_STR_R_THRESHOLD]      = "Schw.: Bewegung ist ein Messwert "
                                   "max(%.3f A, %.0f x Ruherauschen) vom "
                                   "Niveau vor dem Befehl entfernt.",
    [SERVO_STR_R_ARRIVAL]        = "Ankunft: nach einem Messwert eine "
                                   "Schw. über dem Halteniveau der erste "
                                   "wieder innerhalb %.2f A davon.",
    [SERVO_STR_R_BO_HEAD]        = "BROWN-OUT",
    [SERVO_STR_R_BO_NOT_RUN]     = "Nicht gelaufen.",
    [SERVO_STR_R_BO_NOT_REACHED] = "Nicht erreicht.",
    [SERVO_STR_R_BO_STOPPED]     = "Bewegung bei %.2f V; keine Bewegung "
                                   "erkannt bei %.2f V.",
    [SERVO_STR_R_BO_ALL]         = "Bewegung bei jeder Stufe bis %.2f V; "
                                   "tiefer nicht getestet.",
    [SERVO_STR_R_BO_NONE]        = "Keine Bewegung erkannt bei %.2f V, der "
                                   "ersten Stufe: nicht messbar.",
    [SERVO_STR_R_BO_RULE]        = "Keine Bewegung: kein Messwert einer "
                                   "Bewegung mehr als Schw., %.3f A bei "
                                   "%.2f V, vom Niveau davor entfernt.",
    [SERVO_STR_R_LIM_HEAD]       = "VERGLEICH MIT GRENZEN",
    [SERVO_STR_R_LIM_IDLE]       = "Ruhestrom        Höchstwert %.3f A, "
                                   "Grenze %s: %s",
    [SERVO_STR_R_LIM_HOLD]       = "Haltestrom       Höchstwert %.3f A, "
                                   "Grenze %s: %s",
    [SERVO_STR_R_LIM_TRAVEL]     = "Stellzeit        längste %lu ms, Grenze "
                                   "%u ms: %s",
    [SERVO_STR_R_LIM_TRAVEL_OFF] = "Stellzeit        längste %lu ms, Grenze "
                                   "AUS: %s",
    [SERVO_STR_R_LIM_TRAVEL_BOUND] = "Stellzeit        längste %lu ms, "
                                     "Grenze %u ms: Obergrenze, nicht gegen "
                                     "die Grenze geprüft",
    [SERVO_STR_R_LIM_TRAVEL_NONE] = "Stellzeit        längste --, Grenze %s: "
                                    "nicht gemessen, keine Bewegung kam an",
    [SERVO_STR_R_LIM_STALL]      = "Blockierschwelle Höchstwert %.3f A, "
                                   "BLOCKIERT AB %.2f A: %s",
    [SERVO_STR_R_LIM_LATE]       = "Verspätet        %u Bewegungen: %s",
    [SERVO_STR_R_LIM_UNSEEN]     = "Unerkannt        %u Bewegungen: %s",
    [SERVO_STR_R_LIM_BO_SEEN]    = "Brown-out-Start  Bewegung erkannt bei "
                                   "%.2f V: %s",
    [SERVO_STR_R_LIM_BO_UNSEEN]  = "Brown-out-Start  keine Bewegung erkannt "
                                   "bei %.2f V: %s",
    [SERVO_STR_R_NOT_CHECKED]    = "nicht geprüft",
    [SERVO_STR_R_NOT_MEASURED]   = "nicht gemessen",
    [SERVO_STR_R_UNM_HEAD]       = "NICHT GEMESSEN",
    [SERVO_STR_R_UNM_POSITION]   = "Position: nichts misst das Ruderhorn; jedes Ergebnis ist der Strom des Netzteils.",
    [SERVO_STR_R_UNM_PEAKS]      = "Stromspitzen zwischen zwei Messwerten: "
                                   "das Netzteil meldet einen Wert je "
                                   "Messung.",
    [SERVO_STR_R_UNM_PATH]       = "Der Weg des Befehls vom Panel zum Pin, "
                                   "in jeder Stellzeit enthalten.",
    [SERVO_STR_R_ENC_DEVICE]     = "Encoder:         AS5600 an der Hornwelle, "
                                   "Mittenwert %u, %lu Winkelmesswerte",
    [SERVO_STR_R_ENC_HEAD]       = "ENCODER (Winkel in Grad ab dem "
                                   "Mittenwert, Zeiten in ms)",
    /* Over the columns of the encoder lines: 0, 7, 16, 25, 34, 43, 50, 58,
     * 64 and 72, as the English. */
    [SERVO_STR_R_ENC_COLUMNS]    = "Soll V  Ende u   Abw. u   Ende o   Abw. o   "
                                   "Stell. Längste Anz.  Unbew. Spät",
    [SERVO_STR_R_ENC_CMD]        = "Befohlen: %+.1f deg am unteren Ende, %+.1f "
                                   "deg am oberen.",
    [SERVO_STR_R_ENC_END]        = "Ende: der beruhigte Winkel, -180 bis +180 "
                                   "deg ab dem Mittenwert. Abw.: Ende minus "
                                   "befohlen, auf dem kürzeren Weg.",
    [SERVO_STR_R_ENC_SETTLED]    = "Beruhigt: der Winkel blieb %.2f deg "
                                   "innerhalb, %u ms lang.",
    [SERVO_STR_R_ENC_TRAVEL]     = "Stell.: vom Befehl bis zum Beginn dieser "
                                   "Ruhe, mit dem Weg des Befehls vom Panel "
                                   "zum Pin.",
    [SERVO_STR_R_ENC_UNMOVED]    = "Unbew.: der Winkel verließ %.1f deg um "
                                   "den Start nicht.",
    [SERVO_STR_R_ENC_LATE]       = "Spät: der Winkel bewegte sich und war vor "
                                   "dem nächsten Befehl keine %u ms ruhig.",
    [SERVO_STR_R_ENC_DEADBAND]   = "Totband: nicht gemessen; die Bewegungen "
                                   "gehen von Ende zu Ende.",
    [SERVO_STR_R_ENC_NONE]       = "Kein Winkelmesswert erreichte den Lauf.",
    [SERVO_STR_R_ENC_NO_MAGNET]  = "Kein Magnet: AS5600 meldete %lu-mal "
                                   "keinen. Dann kein Winkel im Protokoll, "
                                   "unberuhigte Bewegung nicht gezählt.",
    [SERVO_STR_R_ENC_FIELD]      = "Feld: %lu Messwert(e) mit zu schwachem "
                                   "Magneten, %lu mit zu starkem. Winkel "
                                   "verwendet, Rauschen nicht spezifiziert.",
    [SERVO_STR_R_UNM_POSITION_ENC] = "Position: der AS5600 misst das "
                                     "Ruderhorn; die Stellzeit aus dem Strom "
                                     "steht neben der aus dem Winkel.",

    [SERVO_STR_R_LOG_WIN]        = "Log:             die .CSV mit der Nummer "
                                   "dieser Datei, eine Zeile je Fenster des "
                                   "INA3221",
    [SERVO_STR_R_SUPPLY_PDMINI]  = "PD mini",
    [SERVO_STR_R_CURRENT]        = "Strom:           %s",
    [SERVO_STR_R_CURRENT_INA]    = "Strom:           INA3221 CH1, Shunt %.1f "
                                   "mOhm, Bereich %.3f A",
    [SERVO_STR_R_VOLTAGE]        = "Spannung:        %s",
    [SERVO_STR_R_VOLTAGE_INA]    = "Spannung:        INA3221 CH1, Lastseite "
                                   "des Shunts",
    [SERVO_STR_R_SHUNT]          = "Shunt:           bis %.3f V fallen am "
                                   "Bereichsende an ihm ab; der Sollwert "
                                   "wird dafür nicht angehoben",
    [SERVO_STR_R_INA_UNUSED]     = "INA3221:         nicht verwendet: %s",
    [SERVO_STR_R_INA_OLD]        = "der Koprozessor ist älter als Link-"
                                   "Protokoll 4.11",
    [SERVO_STR_R_INA_NOT_HELD]   = "der Koprozessor hält seine Einstellung "
                                   "nicht",
    [SERVO_STR_R_INA_SILENT]     = "er antwortet nicht",
    [SERVO_STR_R_INA_NO_WINDOW]  = "kein Fenster mit Strom in den letzten "
                                   "200 ms",
    [SERVO_STR_R_INA_RESET]      = "er hat sich zurückgesetzt",
    [SERVO_STR_R_INA_SETTLING]   = "er arbeitet seit weniger als 1 s",
    [SERVO_STR_R_INA_MODEL]      = "das Netzteil ist vom Panel simuliert",
    [SERVO_STR_R_READINGS_WIN]   = "Messwerte:       %.1f /s Fenster vom "
                                   "INA3221 geschlossen, %.1f /s erreichten "
                                   "den Test",
    [SERVO_STR_R_SKIPPED_WIN]    = "Übersprungen:    %lu Fenster des INA3221 "
                                   "erreichten den Test nie",
    [SERVO_STR_R_RESOLUTION_WIN] = "Auflösung:       ein Fenster alle %lu "
                                   "ms: eine Stellzeit ist um bis zu zwei "
                                   "Fenster und den Poll, der sie liest, zu "
                                   "lang",
    [SERVO_STR_R_CLIPPED]        = "Übersteuert:     %lu Fenster enthalten "
                                   "einen Messwert am Bereichsende, %.3f A: "
                                   "ihre Werte sind eine Untergrenze",
    [SERVO_STR_R_CC]             = "Konstantstrom:   %lu Messwerte des "
                                   "Netzteils, längste Folge %lu ms",
    [SERVO_STR_R_NEGATIVE]       = "Strom in Ruhe negativ: Richtung des "
                                   "Shunts",
    [SERVO_STR_R_LIM_STALL_LIMIT] = "BLOCKIERT AB %.2f A unerreichbar: "
                                    "Strombegrenzung %.2f A",
    [SERVO_STR_R_LIM_STALL_RANGE] = "BLOCKIERT AB %.2f A unerreichbar: "
                                    "INA3221-Bereich %.3f A",
    [SERVO_STR_R_UNM_POSITION_INA] = "Position: nichts misst das Ruderhorn; "
                                     "jedes Ergebnis ist der Strom des "
                                     "INA3221 auf CH1.",
    [SERVO_STR_R_UNM_PEAKS_INA]  = "Strom zwischen zwei 1-ms-Messwerten von "
                                   "CH1: ein Fenster enthält deren Mittel, "
                                   "Höchst- und Tiefstwert.",
    [SERVO_STR_R_METER_MODEL]    = "Modell des Panels",
};

const ui_language_t ui_lang_de = {
    .text            = k_text,
    .setting_label   = k_label,
    .setting_help    = k_help,
    .setting_options = k_options,
    .category        = k_category,
    .servo           = k_servo,
};
