#!/usr/bin/env python3
"""Generate the embedded bitmap fonts used by the gfx component.

Renders a monospaced TrueType face into a fixed cell, one byte of coverage
per pixel, so glyph edges arrive antialiased.  Emits one C file per font.

The face is rendered antialiased; each font's threshold is the midpoint of a
contrast ramp, so the font keeps its tuned weight and has a soft edge either
side of it.

A text face holds printable ASCII (0x20 to 0x7E) as one block and, after it,
the extra code points listed in its row of FONTS: the German letters in the
two text faces.  gfx decodes UTF-8 and finds a code point in the block or in
that list; anything else draws as '?'.

    python3 tools/gen_font.py              # regenerate all fonts
    python3 tools/gen_font.py --check      # fail if the checked-in files differ
    python3 tools/gen_font.py --preview 16x28

The generated files are checked in, so the firmware build needs no Python and
no font files.  CI (continuous integration) runs --check so the two cannot
drift apart.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import sys
import unicodedata

from PIL import Image, ImageDraw, ImageFont

# RCBENCH_FONT_DIR first, then the user's own font directory, then the system
# paths.  On a machine without root the system directories cannot be written,
# so the environment variable is what makes the tool runnable there.
FONT_CANDIDATES = [
    p for p in (
        os.path.join(os.environ["RCBENCH_FONT_DIR"], "DejaVuSansMono-Bold.ttf")
        if os.environ.get("RCBENCH_FONT_DIR") else None,
        os.path.expanduser("~/.local/share/fonts/DejaVuSansMono-Bold.ttf"),
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf",
    ) if p
]

# The code points the text faces carry beyond printable ASCII, ascending:
# the German letters.  A language that needs another letter adds it here and
# regenerates; gfx looks a code point up in this list after the ASCII block.
GERMAN = [0xC4, 0xD6, 0xDC, 0xDF, 0xE4, 0xF6, 0xFC]   # Ä Ö Ü ß ä ö ü

# name, cell w, cell h, first, last, ttf size, dx, dy, threshold, output
# file, extra code points
FONTS = [
    ("gfx_font_8x16",      8, 16, 0x20, 0x7E, 13, -1, 0, 110,
     "shared/gfx/gfx_font8x16.c", GERMAN),
    ("gfx_font_16x28",    16, 28, 0x20, 0x7E, 26, -1, 0, 120,
     "shared/gfx/gfx_font16x28.c", GERMAN),
    ("gfx_font_num_24x30", 24, 30, 0x20, 0x3A, 39, -1, -8, 120,
     "shared/gfx/gfx_font_num24x30.c", []),
]

HEADER = """/*
 * Generated by tools/gen_font.py -- do not edit by hand.
 *
 * {name}: {w}x{h} cell, code points 0x{first:02x}..0x{last:02x}{extra_note}.
 * {bpr} bytes per scanline, one byte of coverage per pixel; {h} per glyph.
 *
 * SPDX-License-Identifier: MIT
 */

#include "gfx.h"

static const uint8_t s_glyphs[] = {{
"""

FOOTER = """
const gfx_font_t {name} = {{
    .glyphs        = s_glyphs,
    .width         = {w},
    .height        = {h},
    .bytes_per_row = {bpr},
    .bpp           = 8,
    .first         = 0x{first:02x},
    .last          = 0x{last:02x},
    .extra_count   = {extra_count},
    .extra         = {extra_name},
}};
"""


def pick_font() -> str:
    for path in FONT_CANDIDATES:
        if pathlib.Path(path).exists():
            return path
    sys.exit("no usable monospaced TrueType font found")


def codes(spec) -> list:
    """The code points a font holds, in table order."""
    first, last, extra = spec[3], spec[4], spec[10]
    return list(range(first, last + 1)) + list(extra)


def render(spec) -> dict:
    name, w, h, first, last, size, dx, dy, thr, out, extra = spec
    font = ImageFont.truetype(pick_font(), size)
    glyphs = {}
    # How wide the ramp is either side of the threshold: narrow enough that a
    # stem stays a stem, wide enough that a diagonal is not a staircase, about
    # 1 px of softness at these cell sizes.
    ramp = 62
    lo, hi = thr - ramp, thr + ramp
    for code in codes(spec):
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((dx, dy), chr(code), font=font, fill=255)
        rows = []
        for y in range(h):
            row = bytearray(w)
            for x in range(w):
                v = img.getpixel((x, y))
                # Remapped around the font's threshold, so its weight is
                # unchanged and only its edges soften.
                cov = int(round((v - lo) * 255.0 / (hi - lo)))
                row[x] = 0 if cov < 0 else (255 if cov > 255 else cov)
            rows.append(bytes(row))
        glyphs[code] = rows
    return glyphs


def emit(spec, glyphs) -> str:
    name, w, h, first, last, size, dx, dy, thr, out, extra = spec
    bpr = w
    note = (" and %d more listed in s_extra" % len(extra)) if extra else ""
    parts = [HEADER.format(name=name, w=w, h=h, first=first, last=last,
                           bpr=bpr, extra_note=note)]
    for code in codes(spec):
        if code < 0x80:
            label = repr(chr(code))[1:-1].replace("\\", "\\\\")
            parts.append("    /* 0x%02x '%s' */\n" % (code, label))
        else:
            # The comment stays ASCII: the name, not the letter.
            parts.append("    /* U+%04X %s */\n"
                         % (code, unicodedata.name(chr(code)).lower()))
        for row in glyphs[code]:
            parts.append("    " + " ".join("0x%02x," % b for b in row) + "\n")
    parts.append("};\n")
    if extra:
        parts.append("\nstatic const uint16_t s_extra[] = {\n    "
                     + " ".join("0x%04x," % c for c in extra) + "\n};\n")
    parts.append(FOOTER.format(name=name, w=w, h=h, first=first, last=last,
                               bpr=bpr, extra_count=len(extra),
                               extra_name="s_extra" if extra else "NULL"))
    return "".join(parts)


def preview(spec, glyphs, chars) -> None:
    name, w = spec[0], spec[1]
    for ch in chars:
        code = ord(ch)
        if code not in glyphs:
            continue
        print("--- %s 0x%02x %r" % (name, code, ch))
        for row in glyphs[code]:
            line = "".join("#" if row[x >> 3] & (0x80 >> (x & 7)) else "."
                           for x in range(w))
            print(line)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", metavar="FONT",
                    help="print ASCII art for one font instead of writing")
    ap.add_argument("--chars", default="A8g%.",
                   help="characters to preview")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    failed = False
    for spec in FONTS:
        name, w, h = spec[0], spec[1], spec[2]
        tag = "%dx%d" % (w, h)
        if args.preview and args.preview not in (name, tag):
            continue
        glyphs = render(spec)
        if args.preview:
            preview(spec, glyphs, args.chars)
            continue

        text = emit(spec, glyphs)
        out = pathlib.Path(spec[9])
        if args.check:
            if not out.exists() or out.read_text() != text:
                print("%s is out of date; run tools/gen_font.py" % out,
                      file=sys.stderr)
                failed = True
            else:
                print("%s is up to date" % out)
        else:
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(text)
            print("wrote %s (%d glyphs, %d bytes of table)"
                  % (out, len(glyphs), len(glyphs) * h * w))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
