#!/usr/bin/env python3
"""Generate the board photographs the coprocessor serves over the link.

A panel that has never met a board can ask it for a picture of itself, so the
pin picker shows the thing in the operator's hands rather than an outline of
it.  The picture lives in the coprocessor's own binary as a const array: no
flash store to erase, no wear, and its version is the firmware version.

    python3 tools/gen_board_art.py           # regenerate every board
    python3 tools/gen_board_art.py --check   # and the checked-in files agree

The PNG (portable network graphics) file beside each board is the source and
the C file is generated from it, so the picture can be re-cut without anyone
hand-editing a hundred thousand numbers.  The generated files are checked in,
so the firmware build needs no Python and no image library; CI (continuous
integration) runs --check so the two cannot drift apart.

RGB565 pixels, one uint16_t each.  Pixels rather than bytes because that is
what a picture is, and because a byte costs six characters of source where a
pixel costs eight for two: the table is a third smaller as words.  The link
carries the low byte of each pixel first, and the code serving it does that
split explicitly rather than leaning on the part being little-endian.

The CRC (cyclic
redundancy check) is emitted beside the pixels: the panel checks the whole
payload against it after a transfer that takes about ten seconds, because the
failure worth catching is a block quietly lost and the picture cached wrong.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

from PIL import Image

REPO = pathlib.Path(__file__).resolve().parent.parent

# symbol, source PNG, output C file
BOARDS = [
    ("rp2350_can",
     "firmware/iomcu/artwork/rp2350-can.png",
     "firmware/iomcu/src/art_rp2350_can.c"),
]

# The link's CRC: CCITT polynomial, the same one link_crc.c runs, seeded zero.
def link_crc(data: bytes) -> int:
    crc = 0
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 \
                else (crc << 1) & 0xFFFF
    return crc


HEADER = """/*
 * Generated by tools/gen_board_art.py -- do not edit by hand.
 *
 * {name}: {w} x {h} pixels, RGB565 with the low byte first, {n} bytes.
 * Source: {src}
 *
 * Served over LINK_PAGE_ART_DATA a block at a time.  The CRC below is over
 * the whole payload and is what the panel checks a finished transfer
 * against.
 *
 * SPDX-License-Identifier: MIT
 */

#include <stdint.h>

const uint16_t art_{name}_width  = {w}u;
const uint16_t art_{name}_height = {h}u;
const uint32_t art_{name}_bytes  = {n}u;
const uint16_t art_{name}_crc    = 0x{crc:04X}u;

const uint16_t art_{name}[{px}] = {{
"""

# Appended as it is, so the brace is not doubled the way HEADER's are.
FOOTER = """};
"""


def payload(src: pathlib.Path) -> tuple[list[int], bytes, int, int]:
    """The pixels, and the bytes the link would carry them as."""
    im = Image.open(src).convert("RGB")
    w, h = im.size
    rgb = im.tobytes()
    px, out = [], bytearray()
    for at in range(0, len(rgb), 3):
        r, g, b = rgb[at], rgb[at + 1], rgb[at + 2]
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        px.append(v)
        out.append(v & 0xFF)          # low byte first, as the page carries it
        out.append((v >> 8) & 0xFF)
    return px, bytes(out), w, h


def emit(name: str, src: pathlib.Path, px: list[int], data: bytes,
         w: int, h: int) -> str:
    parts = [HEADER.format(name=name, w=w, h=h, n=len(data), px=len(px),
                           src=src.relative_to(REPO).as_posix(),
                           crc=link_crc(data))]
    # Eight pixels a line, which is 79 columns: the width the rest of the
    # tree keeps to.
    for at in range(0, len(px), 8):
        row = px[at:at + 8]
        parts.append("    " + " ".join("0x%04X," % v for v in row) + "\n")
    parts.append(FOOTER)
    return "".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if a checked-in file differs from its source")
    args = ap.parse_args()

    failed = False
    for name, src_rel, out_rel in BOARDS:
        src = REPO / src_rel
        out = REPO / out_rel
        if not src.exists():
            print("%s is missing" % src_rel, file=sys.stderr)
            failed = True
            continue
        px, data, w, h = payload(src)
        text = emit(name, src, px, data, w, h)
        if args.check:
            if not out.exists() or out.read_text() != text:
                print("%s is out of date; run tools/gen_board_art.py"
                      % out_rel, file=sys.stderr)
                failed = True
            else:
                print("%s is up to date" % out_rel)
        else:
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(text)
            print("wrote %s (%d x %d, %d bytes, crc 0x%04X)"
                  % (out_rel, w, h, len(data), link_crc(data)))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
